// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: microphantom.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_microphantom_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_microphantom_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_microphantom_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_microphantom_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_microphantom_2eproto;
class GameStateBuffer;
struct GameStateBufferDefaultTypeInternal;
extern GameStateBufferDefaultTypeInternal _GameStateBuffer_default_instance_;
class SolutionBuffer;
struct SolutionBufferDefaultTypeInternal;
extern SolutionBufferDefaultTypeInternal _SolutionBuffer_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::GameStateBuffer* Arena::CreateMaybeMessage<::GameStateBuffer>(Arena*);
template<> ::SolutionBuffer* Arena::CreateMaybeMessage<::SolutionBuffer>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class GameStateBuffer final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:GameStateBuffer) */ {
 public:
  inline GameStateBuffer() : GameStateBuffer(nullptr) {}
  ~GameStateBuffer() override;
  explicit constexpr GameStateBuffer(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GameStateBuffer(const GameStateBuffer& from);
  GameStateBuffer(GameStateBuffer&& from) noexcept
    : GameStateBuffer() {
    *this = ::std::move(from);
  }

  inline GameStateBuffer& operator=(const GameStateBuffer& from) {
    CopyFrom(from);
    return *this;
  }
  inline GameStateBuffer& operator=(GameStateBuffer&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GameStateBuffer& default_instance() {
    return *internal_default_instance();
  }
  static inline const GameStateBuffer* internal_default_instance() {
    return reinterpret_cast<const GameStateBuffer*>(
               &_GameStateBuffer_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GameStateBuffer& a, GameStateBuffer& b) {
    a.Swap(&b);
  }
  inline void Swap(GameStateBuffer* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GameStateBuffer* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GameStateBuffer* New() const final {
    return new GameStateBuffer();
  }

  GameStateBuffer* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GameStateBuffer>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GameStateBuffer& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const GameStateBuffer& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GameStateBuffer* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "GameStateBuffer";
  }
  protected:
  explicit GameStateBuffer(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimeFieldNumber = 1,
    kNbBarracksFieldNumber = 2,
    kMinDistanceResourceBaseFieldNumber = 3,
    kMaxDistanceResourceBaseFieldNumber = 4,
    kNoInitialBaseFieldNumber = 5,
    kNoInitialBarracksFieldNumber = 6,
    kResourcesFieldNumber = 7,
    kInitialResourcesFieldNumber = 8,
    kEnemyResourcesLossFieldNumber = 9,
    kWorkerMoveTimeFieldNumber = 10,
    kWorkerHarvestTimeFieldNumber = 11,
    kWorkerReturnTimeFieldNumber = 12,
    kHarvestAmountFieldNumber = 13,
    kBaseCostFieldNumber = 14,
    kBarracksCostFieldNumber = 15,
    kHeavyCostFieldNumber = 16,
    kLightCostFieldNumber = 17,
    kRangedCostFieldNumber = 18,
    kMyHeavyUnitsFieldNumber = 19,
    kMyLightUnitsFieldNumber = 20,
    kMyRangedUnitsFieldNumber = 21,
    kInitialEnemyWorkerFieldNumber = 22,
    kObservedEnemyWorkerFieldNumber = 23,
    kObservedEnemyHeavyFieldNumber = 24,
    kObservedEnemyLightFieldNumber = 25,
    kObservedEnemyRangedFieldNumber = 26,
    kObservedEnemyWorkerInTotalFieldNumber = 27,
    kObservedEnemyHeavyInTotalFieldNumber = 28,
    kObservedEnemyLightInTotalFieldNumber = 29,
    kObservedEnemyRangedInTotalFieldNumber = 30,
    kSolverTypeFieldNumber = 31,
    kNbSamplesFieldNumber = 32,
  };
  // int32 time = 1;
  void clear_time();
  ::PROTOBUF_NAMESPACE_ID::int32 time() const;
  void set_time(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_time() const;
  void _internal_set_time(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 nb_barracks = 2;
  void clear_nb_barracks();
  ::PROTOBUF_NAMESPACE_ID::int32 nb_barracks() const;
  void set_nb_barracks(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_nb_barracks() const;
  void _internal_set_nb_barracks(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 min_distance_resource_base = 3;
  void clear_min_distance_resource_base();
  ::PROTOBUF_NAMESPACE_ID::int32 min_distance_resource_base() const;
  void set_min_distance_resource_base(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_min_distance_resource_base() const;
  void _internal_set_min_distance_resource_base(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 max_distance_resource_base = 4;
  void clear_max_distance_resource_base();
  ::PROTOBUF_NAMESPACE_ID::int32 max_distance_resource_base() const;
  void set_max_distance_resource_base(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_max_distance_resource_base() const;
  void _internal_set_max_distance_resource_base(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 no_initial_base = 5;
  void clear_no_initial_base();
  ::PROTOBUF_NAMESPACE_ID::int32 no_initial_base() const;
  void set_no_initial_base(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_no_initial_base() const;
  void _internal_set_no_initial_base(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 no_initial_barracks = 6;
  void clear_no_initial_barracks();
  ::PROTOBUF_NAMESPACE_ID::int32 no_initial_barracks() const;
  void set_no_initial_barracks(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_no_initial_barracks() const;
  void _internal_set_no_initial_barracks(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 resources = 7;
  void clear_resources();
  ::PROTOBUF_NAMESPACE_ID::int32 resources() const;
  void set_resources(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_resources() const;
  void _internal_set_resources(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 initial_resources = 8;
  void clear_initial_resources();
  ::PROTOBUF_NAMESPACE_ID::int32 initial_resources() const;
  void set_initial_resources(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_initial_resources() const;
  void _internal_set_initial_resources(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 enemy_resources_loss = 9;
  void clear_enemy_resources_loss();
  ::PROTOBUF_NAMESPACE_ID::int32 enemy_resources_loss() const;
  void set_enemy_resources_loss(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_enemy_resources_loss() const;
  void _internal_set_enemy_resources_loss(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 worker_move_time = 10;
  void clear_worker_move_time();
  ::PROTOBUF_NAMESPACE_ID::int32 worker_move_time() const;
  void set_worker_move_time(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_worker_move_time() const;
  void _internal_set_worker_move_time(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 worker_harvest_time = 11;
  void clear_worker_harvest_time();
  ::PROTOBUF_NAMESPACE_ID::int32 worker_harvest_time() const;
  void set_worker_harvest_time(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_worker_harvest_time() const;
  void _internal_set_worker_harvest_time(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 worker_return_time = 12;
  void clear_worker_return_time();
  ::PROTOBUF_NAMESPACE_ID::int32 worker_return_time() const;
  void set_worker_return_time(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_worker_return_time() const;
  void _internal_set_worker_return_time(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 harvest_amount = 13;
  void clear_harvest_amount();
  ::PROTOBUF_NAMESPACE_ID::int32 harvest_amount() const;
  void set_harvest_amount(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_harvest_amount() const;
  void _internal_set_harvest_amount(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 base_cost = 14;
  void clear_base_cost();
  ::PROTOBUF_NAMESPACE_ID::int32 base_cost() const;
  void set_base_cost(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_base_cost() const;
  void _internal_set_base_cost(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 barracks_cost = 15;
  void clear_barracks_cost();
  ::PROTOBUF_NAMESPACE_ID::int32 barracks_cost() const;
  void set_barracks_cost(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_barracks_cost() const;
  void _internal_set_barracks_cost(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 heavy_cost = 16;
  void clear_heavy_cost();
  ::PROTOBUF_NAMESPACE_ID::int32 heavy_cost() const;
  void set_heavy_cost(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_heavy_cost() const;
  void _internal_set_heavy_cost(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 light_cost = 17;
  void clear_light_cost();
  ::PROTOBUF_NAMESPACE_ID::int32 light_cost() const;
  void set_light_cost(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_light_cost() const;
  void _internal_set_light_cost(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 ranged_cost = 18;
  void clear_ranged_cost();
  ::PROTOBUF_NAMESPACE_ID::int32 ranged_cost() const;
  void set_ranged_cost(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_ranged_cost() const;
  void _internal_set_ranged_cost(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 my_heavy_units = 19;
  void clear_my_heavy_units();
  ::PROTOBUF_NAMESPACE_ID::int32 my_heavy_units() const;
  void set_my_heavy_units(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_my_heavy_units() const;
  void _internal_set_my_heavy_units(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 my_light_units = 20;
  void clear_my_light_units();
  ::PROTOBUF_NAMESPACE_ID::int32 my_light_units() const;
  void set_my_light_units(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_my_light_units() const;
  void _internal_set_my_light_units(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 my_ranged_units = 21;
  void clear_my_ranged_units();
  ::PROTOBUF_NAMESPACE_ID::int32 my_ranged_units() const;
  void set_my_ranged_units(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_my_ranged_units() const;
  void _internal_set_my_ranged_units(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 initial_enemy_worker = 22;
  void clear_initial_enemy_worker();
  ::PROTOBUF_NAMESPACE_ID::int32 initial_enemy_worker() const;
  void set_initial_enemy_worker(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_initial_enemy_worker() const;
  void _internal_set_initial_enemy_worker(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 observed_enemy_worker = 23;
  void clear_observed_enemy_worker();
  ::PROTOBUF_NAMESPACE_ID::int32 observed_enemy_worker() const;
  void set_observed_enemy_worker(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_observed_enemy_worker() const;
  void _internal_set_observed_enemy_worker(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 observed_enemy_heavy = 24;
  void clear_observed_enemy_heavy();
  ::PROTOBUF_NAMESPACE_ID::int32 observed_enemy_heavy() const;
  void set_observed_enemy_heavy(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_observed_enemy_heavy() const;
  void _internal_set_observed_enemy_heavy(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 observed_enemy_light = 25;
  void clear_observed_enemy_light();
  ::PROTOBUF_NAMESPACE_ID::int32 observed_enemy_light() const;
  void set_observed_enemy_light(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_observed_enemy_light() const;
  void _internal_set_observed_enemy_light(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 observed_enemy_ranged = 26;
  void clear_observed_enemy_ranged();
  ::PROTOBUF_NAMESPACE_ID::int32 observed_enemy_ranged() const;
  void set_observed_enemy_ranged(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_observed_enemy_ranged() const;
  void _internal_set_observed_enemy_ranged(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 observed_enemy_worker_in_total = 27;
  void clear_observed_enemy_worker_in_total();
  ::PROTOBUF_NAMESPACE_ID::int32 observed_enemy_worker_in_total() const;
  void set_observed_enemy_worker_in_total(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_observed_enemy_worker_in_total() const;
  void _internal_set_observed_enemy_worker_in_total(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 observed_enemy_heavy_in_total = 28;
  void clear_observed_enemy_heavy_in_total();
  ::PROTOBUF_NAMESPACE_ID::int32 observed_enemy_heavy_in_total() const;
  void set_observed_enemy_heavy_in_total(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_observed_enemy_heavy_in_total() const;
  void _internal_set_observed_enemy_heavy_in_total(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 observed_enemy_light_in_total = 29;
  void clear_observed_enemy_light_in_total();
  ::PROTOBUF_NAMESPACE_ID::int32 observed_enemy_light_in_total() const;
  void set_observed_enemy_light_in_total(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_observed_enemy_light_in_total() const;
  void _internal_set_observed_enemy_light_in_total(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 observed_enemy_ranged_in_total = 30;
  void clear_observed_enemy_ranged_in_total();
  ::PROTOBUF_NAMESPACE_ID::int32 observed_enemy_ranged_in_total() const;
  void set_observed_enemy_ranged_in_total(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_observed_enemy_ranged_in_total() const;
  void _internal_set_observed_enemy_ranged_in_total(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 solver_type = 31;
  void clear_solver_type();
  ::PROTOBUF_NAMESPACE_ID::int32 solver_type() const;
  void set_solver_type(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_solver_type() const;
  void _internal_set_solver_type(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 nb_samples = 32;
  void clear_nb_samples();
  ::PROTOBUF_NAMESPACE_ID::int32 nb_samples() const;
  void set_nb_samples(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_nb_samples() const;
  void _internal_set_nb_samples(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:GameStateBuffer)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 time_;
  ::PROTOBUF_NAMESPACE_ID::int32 nb_barracks_;
  ::PROTOBUF_NAMESPACE_ID::int32 min_distance_resource_base_;
  ::PROTOBUF_NAMESPACE_ID::int32 max_distance_resource_base_;
  ::PROTOBUF_NAMESPACE_ID::int32 no_initial_base_;
  ::PROTOBUF_NAMESPACE_ID::int32 no_initial_barracks_;
  ::PROTOBUF_NAMESPACE_ID::int32 resources_;
  ::PROTOBUF_NAMESPACE_ID::int32 initial_resources_;
  ::PROTOBUF_NAMESPACE_ID::int32 enemy_resources_loss_;
  ::PROTOBUF_NAMESPACE_ID::int32 worker_move_time_;
  ::PROTOBUF_NAMESPACE_ID::int32 worker_harvest_time_;
  ::PROTOBUF_NAMESPACE_ID::int32 worker_return_time_;
  ::PROTOBUF_NAMESPACE_ID::int32 harvest_amount_;
  ::PROTOBUF_NAMESPACE_ID::int32 base_cost_;
  ::PROTOBUF_NAMESPACE_ID::int32 barracks_cost_;
  ::PROTOBUF_NAMESPACE_ID::int32 heavy_cost_;
  ::PROTOBUF_NAMESPACE_ID::int32 light_cost_;
  ::PROTOBUF_NAMESPACE_ID::int32 ranged_cost_;
  ::PROTOBUF_NAMESPACE_ID::int32 my_heavy_units_;
  ::PROTOBUF_NAMESPACE_ID::int32 my_light_units_;
  ::PROTOBUF_NAMESPACE_ID::int32 my_ranged_units_;
  ::PROTOBUF_NAMESPACE_ID::int32 initial_enemy_worker_;
  ::PROTOBUF_NAMESPACE_ID::int32 observed_enemy_worker_;
  ::PROTOBUF_NAMESPACE_ID::int32 observed_enemy_heavy_;
  ::PROTOBUF_NAMESPACE_ID::int32 observed_enemy_light_;
  ::PROTOBUF_NAMESPACE_ID::int32 observed_enemy_ranged_;
  ::PROTOBUF_NAMESPACE_ID::int32 observed_enemy_worker_in_total_;
  ::PROTOBUF_NAMESPACE_ID::int32 observed_enemy_heavy_in_total_;
  ::PROTOBUF_NAMESPACE_ID::int32 observed_enemy_light_in_total_;
  ::PROTOBUF_NAMESPACE_ID::int32 observed_enemy_ranged_in_total_;
  ::PROTOBUF_NAMESPACE_ID::int32 solver_type_;
  ::PROTOBUF_NAMESPACE_ID::int32 nb_samples_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_microphantom_2eproto;
};
// -------------------------------------------------------------------

class SolutionBuffer final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SolutionBuffer) */ {
 public:
  inline SolutionBuffer() : SolutionBuffer(nullptr) {}
  ~SolutionBuffer() override;
  explicit constexpr SolutionBuffer(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SolutionBuffer(const SolutionBuffer& from);
  SolutionBuffer(SolutionBuffer&& from) noexcept
    : SolutionBuffer() {
    *this = ::std::move(from);
  }

  inline SolutionBuffer& operator=(const SolutionBuffer& from) {
    CopyFrom(from);
    return *this;
  }
  inline SolutionBuffer& operator=(SolutionBuffer&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SolutionBuffer& default_instance() {
    return *internal_default_instance();
  }
  static inline const SolutionBuffer* internal_default_instance() {
    return reinterpret_cast<const SolutionBuffer*>(
               &_SolutionBuffer_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SolutionBuffer& a, SolutionBuffer& b) {
    a.Swap(&b);
  }
  inline void Swap(SolutionBuffer* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SolutionBuffer* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SolutionBuffer* New() const final {
    return new SolutionBuffer();
  }

  SolutionBuffer* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SolutionBuffer>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SolutionBuffer& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const SolutionBuffer& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SolutionBuffer* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SolutionBuffer";
  }
  protected:
  explicit SolutionBuffer(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNumberHeavyFieldNumber = 1,
    kNumberLightFieldNumber = 2,
    kNumberRangedFieldNumber = 3,
  };
  // int32 number_heavy = 1;
  void clear_number_heavy();
  ::PROTOBUF_NAMESPACE_ID::int32 number_heavy() const;
  void set_number_heavy(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_number_heavy() const;
  void _internal_set_number_heavy(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 number_light = 2;
  void clear_number_light();
  ::PROTOBUF_NAMESPACE_ID::int32 number_light() const;
  void set_number_light(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_number_light() const;
  void _internal_set_number_light(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 number_ranged = 3;
  void clear_number_ranged();
  ::PROTOBUF_NAMESPACE_ID::int32 number_ranged() const;
  void set_number_ranged(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_number_ranged() const;
  void _internal_set_number_ranged(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:SolutionBuffer)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 number_heavy_;
  ::PROTOBUF_NAMESPACE_ID::int32 number_light_;
  ::PROTOBUF_NAMESPACE_ID::int32 number_ranged_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_microphantom_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GameStateBuffer

// int32 time = 1;
inline void GameStateBuffer::clear_time() {
  time_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::_internal_time() const {
  return time_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::time() const {
  // @@protoc_insertion_point(field_get:GameStateBuffer.time)
  return _internal_time();
}
inline void GameStateBuffer::_internal_set_time(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  time_ = value;
}
inline void GameStateBuffer::set_time(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_time(value);
  // @@protoc_insertion_point(field_set:GameStateBuffer.time)
}

// int32 nb_barracks = 2;
inline void GameStateBuffer::clear_nb_barracks() {
  nb_barracks_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::_internal_nb_barracks() const {
  return nb_barracks_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::nb_barracks() const {
  // @@protoc_insertion_point(field_get:GameStateBuffer.nb_barracks)
  return _internal_nb_barracks();
}
inline void GameStateBuffer::_internal_set_nb_barracks(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  nb_barracks_ = value;
}
inline void GameStateBuffer::set_nb_barracks(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_nb_barracks(value);
  // @@protoc_insertion_point(field_set:GameStateBuffer.nb_barracks)
}

// int32 min_distance_resource_base = 3;
inline void GameStateBuffer::clear_min_distance_resource_base() {
  min_distance_resource_base_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::_internal_min_distance_resource_base() const {
  return min_distance_resource_base_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::min_distance_resource_base() const {
  // @@protoc_insertion_point(field_get:GameStateBuffer.min_distance_resource_base)
  return _internal_min_distance_resource_base();
}
inline void GameStateBuffer::_internal_set_min_distance_resource_base(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  min_distance_resource_base_ = value;
}
inline void GameStateBuffer::set_min_distance_resource_base(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_min_distance_resource_base(value);
  // @@protoc_insertion_point(field_set:GameStateBuffer.min_distance_resource_base)
}

// int32 max_distance_resource_base = 4;
inline void GameStateBuffer::clear_max_distance_resource_base() {
  max_distance_resource_base_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::_internal_max_distance_resource_base() const {
  return max_distance_resource_base_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::max_distance_resource_base() const {
  // @@protoc_insertion_point(field_get:GameStateBuffer.max_distance_resource_base)
  return _internal_max_distance_resource_base();
}
inline void GameStateBuffer::_internal_set_max_distance_resource_base(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  max_distance_resource_base_ = value;
}
inline void GameStateBuffer::set_max_distance_resource_base(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_max_distance_resource_base(value);
  // @@protoc_insertion_point(field_set:GameStateBuffer.max_distance_resource_base)
}

// int32 no_initial_base = 5;
inline void GameStateBuffer::clear_no_initial_base() {
  no_initial_base_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::_internal_no_initial_base() const {
  return no_initial_base_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::no_initial_base() const {
  // @@protoc_insertion_point(field_get:GameStateBuffer.no_initial_base)
  return _internal_no_initial_base();
}
inline void GameStateBuffer::_internal_set_no_initial_base(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  no_initial_base_ = value;
}
inline void GameStateBuffer::set_no_initial_base(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_no_initial_base(value);
  // @@protoc_insertion_point(field_set:GameStateBuffer.no_initial_base)
}

// int32 no_initial_barracks = 6;
inline void GameStateBuffer::clear_no_initial_barracks() {
  no_initial_barracks_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::_internal_no_initial_barracks() const {
  return no_initial_barracks_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::no_initial_barracks() const {
  // @@protoc_insertion_point(field_get:GameStateBuffer.no_initial_barracks)
  return _internal_no_initial_barracks();
}
inline void GameStateBuffer::_internal_set_no_initial_barracks(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  no_initial_barracks_ = value;
}
inline void GameStateBuffer::set_no_initial_barracks(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_no_initial_barracks(value);
  // @@protoc_insertion_point(field_set:GameStateBuffer.no_initial_barracks)
}

// int32 resources = 7;
inline void GameStateBuffer::clear_resources() {
  resources_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::_internal_resources() const {
  return resources_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::resources() const {
  // @@protoc_insertion_point(field_get:GameStateBuffer.resources)
  return _internal_resources();
}
inline void GameStateBuffer::_internal_set_resources(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  resources_ = value;
}
inline void GameStateBuffer::set_resources(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_resources(value);
  // @@protoc_insertion_point(field_set:GameStateBuffer.resources)
}

// int32 initial_resources = 8;
inline void GameStateBuffer::clear_initial_resources() {
  initial_resources_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::_internal_initial_resources() const {
  return initial_resources_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::initial_resources() const {
  // @@protoc_insertion_point(field_get:GameStateBuffer.initial_resources)
  return _internal_initial_resources();
}
inline void GameStateBuffer::_internal_set_initial_resources(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  initial_resources_ = value;
}
inline void GameStateBuffer::set_initial_resources(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_initial_resources(value);
  // @@protoc_insertion_point(field_set:GameStateBuffer.initial_resources)
}

// int32 enemy_resources_loss = 9;
inline void GameStateBuffer::clear_enemy_resources_loss() {
  enemy_resources_loss_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::_internal_enemy_resources_loss() const {
  return enemy_resources_loss_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::enemy_resources_loss() const {
  // @@protoc_insertion_point(field_get:GameStateBuffer.enemy_resources_loss)
  return _internal_enemy_resources_loss();
}
inline void GameStateBuffer::_internal_set_enemy_resources_loss(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  enemy_resources_loss_ = value;
}
inline void GameStateBuffer::set_enemy_resources_loss(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_enemy_resources_loss(value);
  // @@protoc_insertion_point(field_set:GameStateBuffer.enemy_resources_loss)
}

// int32 worker_move_time = 10;
inline void GameStateBuffer::clear_worker_move_time() {
  worker_move_time_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::_internal_worker_move_time() const {
  return worker_move_time_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::worker_move_time() const {
  // @@protoc_insertion_point(field_get:GameStateBuffer.worker_move_time)
  return _internal_worker_move_time();
}
inline void GameStateBuffer::_internal_set_worker_move_time(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  worker_move_time_ = value;
}
inline void GameStateBuffer::set_worker_move_time(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_worker_move_time(value);
  // @@protoc_insertion_point(field_set:GameStateBuffer.worker_move_time)
}

// int32 worker_harvest_time = 11;
inline void GameStateBuffer::clear_worker_harvest_time() {
  worker_harvest_time_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::_internal_worker_harvest_time() const {
  return worker_harvest_time_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::worker_harvest_time() const {
  // @@protoc_insertion_point(field_get:GameStateBuffer.worker_harvest_time)
  return _internal_worker_harvest_time();
}
inline void GameStateBuffer::_internal_set_worker_harvest_time(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  worker_harvest_time_ = value;
}
inline void GameStateBuffer::set_worker_harvest_time(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_worker_harvest_time(value);
  // @@protoc_insertion_point(field_set:GameStateBuffer.worker_harvest_time)
}

// int32 worker_return_time = 12;
inline void GameStateBuffer::clear_worker_return_time() {
  worker_return_time_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::_internal_worker_return_time() const {
  return worker_return_time_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::worker_return_time() const {
  // @@protoc_insertion_point(field_get:GameStateBuffer.worker_return_time)
  return _internal_worker_return_time();
}
inline void GameStateBuffer::_internal_set_worker_return_time(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  worker_return_time_ = value;
}
inline void GameStateBuffer::set_worker_return_time(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_worker_return_time(value);
  // @@protoc_insertion_point(field_set:GameStateBuffer.worker_return_time)
}

// int32 harvest_amount = 13;
inline void GameStateBuffer::clear_harvest_amount() {
  harvest_amount_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::_internal_harvest_amount() const {
  return harvest_amount_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::harvest_amount() const {
  // @@protoc_insertion_point(field_get:GameStateBuffer.harvest_amount)
  return _internal_harvest_amount();
}
inline void GameStateBuffer::_internal_set_harvest_amount(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  harvest_amount_ = value;
}
inline void GameStateBuffer::set_harvest_amount(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_harvest_amount(value);
  // @@protoc_insertion_point(field_set:GameStateBuffer.harvest_amount)
}

// int32 base_cost = 14;
inline void GameStateBuffer::clear_base_cost() {
  base_cost_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::_internal_base_cost() const {
  return base_cost_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::base_cost() const {
  // @@protoc_insertion_point(field_get:GameStateBuffer.base_cost)
  return _internal_base_cost();
}
inline void GameStateBuffer::_internal_set_base_cost(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  base_cost_ = value;
}
inline void GameStateBuffer::set_base_cost(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_base_cost(value);
  // @@protoc_insertion_point(field_set:GameStateBuffer.base_cost)
}

// int32 barracks_cost = 15;
inline void GameStateBuffer::clear_barracks_cost() {
  barracks_cost_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::_internal_barracks_cost() const {
  return barracks_cost_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::barracks_cost() const {
  // @@protoc_insertion_point(field_get:GameStateBuffer.barracks_cost)
  return _internal_barracks_cost();
}
inline void GameStateBuffer::_internal_set_barracks_cost(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  barracks_cost_ = value;
}
inline void GameStateBuffer::set_barracks_cost(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_barracks_cost(value);
  // @@protoc_insertion_point(field_set:GameStateBuffer.barracks_cost)
}

// int32 heavy_cost = 16;
inline void GameStateBuffer::clear_heavy_cost() {
  heavy_cost_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::_internal_heavy_cost() const {
  return heavy_cost_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::heavy_cost() const {
  // @@protoc_insertion_point(field_get:GameStateBuffer.heavy_cost)
  return _internal_heavy_cost();
}
inline void GameStateBuffer::_internal_set_heavy_cost(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  heavy_cost_ = value;
}
inline void GameStateBuffer::set_heavy_cost(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_heavy_cost(value);
  // @@protoc_insertion_point(field_set:GameStateBuffer.heavy_cost)
}

// int32 light_cost = 17;
inline void GameStateBuffer::clear_light_cost() {
  light_cost_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::_internal_light_cost() const {
  return light_cost_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::light_cost() const {
  // @@protoc_insertion_point(field_get:GameStateBuffer.light_cost)
  return _internal_light_cost();
}
inline void GameStateBuffer::_internal_set_light_cost(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  light_cost_ = value;
}
inline void GameStateBuffer::set_light_cost(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_light_cost(value);
  // @@protoc_insertion_point(field_set:GameStateBuffer.light_cost)
}

// int32 ranged_cost = 18;
inline void GameStateBuffer::clear_ranged_cost() {
  ranged_cost_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::_internal_ranged_cost() const {
  return ranged_cost_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::ranged_cost() const {
  // @@protoc_insertion_point(field_get:GameStateBuffer.ranged_cost)
  return _internal_ranged_cost();
}
inline void GameStateBuffer::_internal_set_ranged_cost(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  ranged_cost_ = value;
}
inline void GameStateBuffer::set_ranged_cost(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_ranged_cost(value);
  // @@protoc_insertion_point(field_set:GameStateBuffer.ranged_cost)
}

// int32 my_heavy_units = 19;
inline void GameStateBuffer::clear_my_heavy_units() {
  my_heavy_units_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::_internal_my_heavy_units() const {
  return my_heavy_units_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::my_heavy_units() const {
  // @@protoc_insertion_point(field_get:GameStateBuffer.my_heavy_units)
  return _internal_my_heavy_units();
}
inline void GameStateBuffer::_internal_set_my_heavy_units(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  my_heavy_units_ = value;
}
inline void GameStateBuffer::set_my_heavy_units(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_my_heavy_units(value);
  // @@protoc_insertion_point(field_set:GameStateBuffer.my_heavy_units)
}

// int32 my_light_units = 20;
inline void GameStateBuffer::clear_my_light_units() {
  my_light_units_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::_internal_my_light_units() const {
  return my_light_units_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::my_light_units() const {
  // @@protoc_insertion_point(field_get:GameStateBuffer.my_light_units)
  return _internal_my_light_units();
}
inline void GameStateBuffer::_internal_set_my_light_units(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  my_light_units_ = value;
}
inline void GameStateBuffer::set_my_light_units(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_my_light_units(value);
  // @@protoc_insertion_point(field_set:GameStateBuffer.my_light_units)
}

// int32 my_ranged_units = 21;
inline void GameStateBuffer::clear_my_ranged_units() {
  my_ranged_units_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::_internal_my_ranged_units() const {
  return my_ranged_units_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::my_ranged_units() const {
  // @@protoc_insertion_point(field_get:GameStateBuffer.my_ranged_units)
  return _internal_my_ranged_units();
}
inline void GameStateBuffer::_internal_set_my_ranged_units(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  my_ranged_units_ = value;
}
inline void GameStateBuffer::set_my_ranged_units(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_my_ranged_units(value);
  // @@protoc_insertion_point(field_set:GameStateBuffer.my_ranged_units)
}

// int32 initial_enemy_worker = 22;
inline void GameStateBuffer::clear_initial_enemy_worker() {
  initial_enemy_worker_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::_internal_initial_enemy_worker() const {
  return initial_enemy_worker_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::initial_enemy_worker() const {
  // @@protoc_insertion_point(field_get:GameStateBuffer.initial_enemy_worker)
  return _internal_initial_enemy_worker();
}
inline void GameStateBuffer::_internal_set_initial_enemy_worker(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  initial_enemy_worker_ = value;
}
inline void GameStateBuffer::set_initial_enemy_worker(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_initial_enemy_worker(value);
  // @@protoc_insertion_point(field_set:GameStateBuffer.initial_enemy_worker)
}

// int32 observed_enemy_worker = 23;
inline void GameStateBuffer::clear_observed_enemy_worker() {
  observed_enemy_worker_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::_internal_observed_enemy_worker() const {
  return observed_enemy_worker_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::observed_enemy_worker() const {
  // @@protoc_insertion_point(field_get:GameStateBuffer.observed_enemy_worker)
  return _internal_observed_enemy_worker();
}
inline void GameStateBuffer::_internal_set_observed_enemy_worker(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  observed_enemy_worker_ = value;
}
inline void GameStateBuffer::set_observed_enemy_worker(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_observed_enemy_worker(value);
  // @@protoc_insertion_point(field_set:GameStateBuffer.observed_enemy_worker)
}

// int32 observed_enemy_heavy = 24;
inline void GameStateBuffer::clear_observed_enemy_heavy() {
  observed_enemy_heavy_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::_internal_observed_enemy_heavy() const {
  return observed_enemy_heavy_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::observed_enemy_heavy() const {
  // @@protoc_insertion_point(field_get:GameStateBuffer.observed_enemy_heavy)
  return _internal_observed_enemy_heavy();
}
inline void GameStateBuffer::_internal_set_observed_enemy_heavy(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  observed_enemy_heavy_ = value;
}
inline void GameStateBuffer::set_observed_enemy_heavy(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_observed_enemy_heavy(value);
  // @@protoc_insertion_point(field_set:GameStateBuffer.observed_enemy_heavy)
}

// int32 observed_enemy_light = 25;
inline void GameStateBuffer::clear_observed_enemy_light() {
  observed_enemy_light_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::_internal_observed_enemy_light() const {
  return observed_enemy_light_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::observed_enemy_light() const {
  // @@protoc_insertion_point(field_get:GameStateBuffer.observed_enemy_light)
  return _internal_observed_enemy_light();
}
inline void GameStateBuffer::_internal_set_observed_enemy_light(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  observed_enemy_light_ = value;
}
inline void GameStateBuffer::set_observed_enemy_light(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_observed_enemy_light(value);
  // @@protoc_insertion_point(field_set:GameStateBuffer.observed_enemy_light)
}

// int32 observed_enemy_ranged = 26;
inline void GameStateBuffer::clear_observed_enemy_ranged() {
  observed_enemy_ranged_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::_internal_observed_enemy_ranged() const {
  return observed_enemy_ranged_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::observed_enemy_ranged() const {
  // @@protoc_insertion_point(field_get:GameStateBuffer.observed_enemy_ranged)
  return _internal_observed_enemy_ranged();
}
inline void GameStateBuffer::_internal_set_observed_enemy_ranged(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  observed_enemy_ranged_ = value;
}
inline void GameStateBuffer::set_observed_enemy_ranged(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_observed_enemy_ranged(value);
  // @@protoc_insertion_point(field_set:GameStateBuffer.observed_enemy_ranged)
}

// int32 observed_enemy_worker_in_total = 27;
inline void GameStateBuffer::clear_observed_enemy_worker_in_total() {
  observed_enemy_worker_in_total_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::_internal_observed_enemy_worker_in_total() const {
  return observed_enemy_worker_in_total_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::observed_enemy_worker_in_total() const {
  // @@protoc_insertion_point(field_get:GameStateBuffer.observed_enemy_worker_in_total)
  return _internal_observed_enemy_worker_in_total();
}
inline void GameStateBuffer::_internal_set_observed_enemy_worker_in_total(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  observed_enemy_worker_in_total_ = value;
}
inline void GameStateBuffer::set_observed_enemy_worker_in_total(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_observed_enemy_worker_in_total(value);
  // @@protoc_insertion_point(field_set:GameStateBuffer.observed_enemy_worker_in_total)
}

// int32 observed_enemy_heavy_in_total = 28;
inline void GameStateBuffer::clear_observed_enemy_heavy_in_total() {
  observed_enemy_heavy_in_total_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::_internal_observed_enemy_heavy_in_total() const {
  return observed_enemy_heavy_in_total_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::observed_enemy_heavy_in_total() const {
  // @@protoc_insertion_point(field_get:GameStateBuffer.observed_enemy_heavy_in_total)
  return _internal_observed_enemy_heavy_in_total();
}
inline void GameStateBuffer::_internal_set_observed_enemy_heavy_in_total(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  observed_enemy_heavy_in_total_ = value;
}
inline void GameStateBuffer::set_observed_enemy_heavy_in_total(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_observed_enemy_heavy_in_total(value);
  // @@protoc_insertion_point(field_set:GameStateBuffer.observed_enemy_heavy_in_total)
}

// int32 observed_enemy_light_in_total = 29;
inline void GameStateBuffer::clear_observed_enemy_light_in_total() {
  observed_enemy_light_in_total_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::_internal_observed_enemy_light_in_total() const {
  return observed_enemy_light_in_total_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::observed_enemy_light_in_total() const {
  // @@protoc_insertion_point(field_get:GameStateBuffer.observed_enemy_light_in_total)
  return _internal_observed_enemy_light_in_total();
}
inline void GameStateBuffer::_internal_set_observed_enemy_light_in_total(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  observed_enemy_light_in_total_ = value;
}
inline void GameStateBuffer::set_observed_enemy_light_in_total(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_observed_enemy_light_in_total(value);
  // @@protoc_insertion_point(field_set:GameStateBuffer.observed_enemy_light_in_total)
}

// int32 observed_enemy_ranged_in_total = 30;
inline void GameStateBuffer::clear_observed_enemy_ranged_in_total() {
  observed_enemy_ranged_in_total_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::_internal_observed_enemy_ranged_in_total() const {
  return observed_enemy_ranged_in_total_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::observed_enemy_ranged_in_total() const {
  // @@protoc_insertion_point(field_get:GameStateBuffer.observed_enemy_ranged_in_total)
  return _internal_observed_enemy_ranged_in_total();
}
inline void GameStateBuffer::_internal_set_observed_enemy_ranged_in_total(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  observed_enemy_ranged_in_total_ = value;
}
inline void GameStateBuffer::set_observed_enemy_ranged_in_total(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_observed_enemy_ranged_in_total(value);
  // @@protoc_insertion_point(field_set:GameStateBuffer.observed_enemy_ranged_in_total)
}

// int32 solver_type = 31;
inline void GameStateBuffer::clear_solver_type() {
  solver_type_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::_internal_solver_type() const {
  return solver_type_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::solver_type() const {
  // @@protoc_insertion_point(field_get:GameStateBuffer.solver_type)
  return _internal_solver_type();
}
inline void GameStateBuffer::_internal_set_solver_type(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  solver_type_ = value;
}
inline void GameStateBuffer::set_solver_type(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_solver_type(value);
  // @@protoc_insertion_point(field_set:GameStateBuffer.solver_type)
}

// int32 nb_samples = 32;
inline void GameStateBuffer::clear_nb_samples() {
  nb_samples_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::_internal_nb_samples() const {
  return nb_samples_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameStateBuffer::nb_samples() const {
  // @@protoc_insertion_point(field_get:GameStateBuffer.nb_samples)
  return _internal_nb_samples();
}
inline void GameStateBuffer::_internal_set_nb_samples(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  nb_samples_ = value;
}
inline void GameStateBuffer::set_nb_samples(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_nb_samples(value);
  // @@protoc_insertion_point(field_set:GameStateBuffer.nb_samples)
}

// -------------------------------------------------------------------

// SolutionBuffer

// int32 number_heavy = 1;
inline void SolutionBuffer::clear_number_heavy() {
  number_heavy_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SolutionBuffer::_internal_number_heavy() const {
  return number_heavy_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SolutionBuffer::number_heavy() const {
  // @@protoc_insertion_point(field_get:SolutionBuffer.number_heavy)
  return _internal_number_heavy();
}
inline void SolutionBuffer::_internal_set_number_heavy(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  number_heavy_ = value;
}
inline void SolutionBuffer::set_number_heavy(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_number_heavy(value);
  // @@protoc_insertion_point(field_set:SolutionBuffer.number_heavy)
}

// int32 number_light = 2;
inline void SolutionBuffer::clear_number_light() {
  number_light_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SolutionBuffer::_internal_number_light() const {
  return number_light_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SolutionBuffer::number_light() const {
  // @@protoc_insertion_point(field_get:SolutionBuffer.number_light)
  return _internal_number_light();
}
inline void SolutionBuffer::_internal_set_number_light(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  number_light_ = value;
}
inline void SolutionBuffer::set_number_light(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_number_light(value);
  // @@protoc_insertion_point(field_set:SolutionBuffer.number_light)
}

// int32 number_ranged = 3;
inline void SolutionBuffer::clear_number_ranged() {
  number_ranged_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SolutionBuffer::_internal_number_ranged() const {
  return number_ranged_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SolutionBuffer::number_ranged() const {
  // @@protoc_insertion_point(field_get:SolutionBuffer.number_ranged)
  return _internal_number_ranged();
}
inline void SolutionBuffer::_internal_set_number_ranged(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  number_ranged_ = value;
}
inline void SolutionBuffer::set_number_ranged(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_number_ranged(value);
  // @@protoc_insertion_point(field_set:SolutionBuffer.number_ranged)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_microphantom_2eproto
