// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: microphantom.proto

package com.microphantom.protos;

/**
 * Protobuf type {@code GameStateBuffer}
 */
public final class GameStateBuffer extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GameStateBuffer)
    GameStateBufferOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GameStateBuffer.newBuilder() to construct.
  private GameStateBuffer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GameStateBuffer() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GameStateBuffer();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GameStateBuffer(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            time_ = input.readInt32();
            break;
          }
          case 16: {

            nbBarracks_ = input.readInt32();
            break;
          }
          case 24: {

            minDistanceResourceBase_ = input.readInt32();
            break;
          }
          case 32: {

            maxDistanceResourceBase_ = input.readInt32();
            break;
          }
          case 40: {

            noInitialBase_ = input.readInt32();
            break;
          }
          case 48: {

            noInitialBarracks_ = input.readInt32();
            break;
          }
          case 56: {

            resources_ = input.readInt32();
            break;
          }
          case 64: {

            initialResources_ = input.readInt32();
            break;
          }
          case 72: {

            enemyResourcesLoss_ = input.readInt32();
            break;
          }
          case 80: {

            workerMoveTime_ = input.readInt32();
            break;
          }
          case 88: {

            workerHarvestTime_ = input.readInt32();
            break;
          }
          case 96: {

            workerReturnTime_ = input.readInt32();
            break;
          }
          case 104: {

            harvestAmount_ = input.readInt32();
            break;
          }
          case 112: {

            baseCost_ = input.readInt32();
            break;
          }
          case 120: {

            barracksCost_ = input.readInt32();
            break;
          }
          case 128: {

            heavyCost_ = input.readInt32();
            break;
          }
          case 136: {

            lightCost_ = input.readInt32();
            break;
          }
          case 144: {

            rangedCost_ = input.readInt32();
            break;
          }
          case 152: {

            myHeavyUnits_ = input.readInt32();
            break;
          }
          case 160: {

            myLightUnits_ = input.readInt32();
            break;
          }
          case 168: {

            myRangedUnits_ = input.readInt32();
            break;
          }
          case 176: {

            initialEnemyWorker_ = input.readInt32();
            break;
          }
          case 184: {

            observedEnemyWorker_ = input.readInt32();
            break;
          }
          case 192: {

            observedEnemyHeavy_ = input.readInt32();
            break;
          }
          case 200: {

            observedEnemyLight_ = input.readInt32();
            break;
          }
          case 208: {

            observedEnemyRanged_ = input.readInt32();
            break;
          }
          case 216: {

            observedEnemyWorkerInTotal_ = input.readInt32();
            break;
          }
          case 224: {

            observedEnemyHeavyInTotal_ = input.readInt32();
            break;
          }
          case 232: {

            observedEnemyLightInTotal_ = input.readInt32();
            break;
          }
          case 240: {

            observedEnemyRangedInTotal_ = input.readInt32();
            break;
          }
          case 248: {

            solverType_ = input.readInt32();
            break;
          }
          case 256: {

            nbSamples_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.microphantom.protos.MicroPhantomProtos.internal_static_GameStateBuffer_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.microphantom.protos.MicroPhantomProtos.internal_static_GameStateBuffer_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.microphantom.protos.GameStateBuffer.class, com.microphantom.protos.GameStateBuffer.Builder.class);
  }

  public static final int TIME_FIELD_NUMBER = 1;
  private int time_;
  /**
   * <code>int32 time = 1;</code>
   * @return The time.
   */
  @java.lang.Override
  public int getTime() {
    return time_;
  }

  public static final int NB_BARRACKS_FIELD_NUMBER = 2;
  private int nbBarracks_;
  /**
   * <code>int32 nb_barracks = 2;</code>
   * @return The nbBarracks.
   */
  @java.lang.Override
  public int getNbBarracks() {
    return nbBarracks_;
  }

  public static final int MIN_DISTANCE_RESOURCE_BASE_FIELD_NUMBER = 3;
  private int minDistanceResourceBase_;
  /**
   * <code>int32 min_distance_resource_base = 3;</code>
   * @return The minDistanceResourceBase.
   */
  @java.lang.Override
  public int getMinDistanceResourceBase() {
    return minDistanceResourceBase_;
  }

  public static final int MAX_DISTANCE_RESOURCE_BASE_FIELD_NUMBER = 4;
  private int maxDistanceResourceBase_;
  /**
   * <code>int32 max_distance_resource_base = 4;</code>
   * @return The maxDistanceResourceBase.
   */
  @java.lang.Override
  public int getMaxDistanceResourceBase() {
    return maxDistanceResourceBase_;
  }

  public static final int NO_INITIAL_BASE_FIELD_NUMBER = 5;
  private int noInitialBase_;
  /**
   * <code>int32 no_initial_base = 5;</code>
   * @return The noInitialBase.
   */
  @java.lang.Override
  public int getNoInitialBase() {
    return noInitialBase_;
  }

  public static final int NO_INITIAL_BARRACKS_FIELD_NUMBER = 6;
  private int noInitialBarracks_;
  /**
   * <code>int32 no_initial_barracks = 6;</code>
   * @return The noInitialBarracks.
   */
  @java.lang.Override
  public int getNoInitialBarracks() {
    return noInitialBarracks_;
  }

  public static final int RESOURCES_FIELD_NUMBER = 7;
  private int resources_;
  /**
   * <code>int32 resources = 7;</code>
   * @return The resources.
   */
  @java.lang.Override
  public int getResources() {
    return resources_;
  }

  public static final int INITIAL_RESOURCES_FIELD_NUMBER = 8;
  private int initialResources_;
  /**
   * <code>int32 initial_resources = 8;</code>
   * @return The initialResources.
   */
  @java.lang.Override
  public int getInitialResources() {
    return initialResources_;
  }

  public static final int ENEMY_RESOURCES_LOSS_FIELD_NUMBER = 9;
  private int enemyResourcesLoss_;
  /**
   * <code>int32 enemy_resources_loss = 9;</code>
   * @return The enemyResourcesLoss.
   */
  @java.lang.Override
  public int getEnemyResourcesLoss() {
    return enemyResourcesLoss_;
  }

  public static final int WORKER_MOVE_TIME_FIELD_NUMBER = 10;
  private int workerMoveTime_;
  /**
   * <code>int32 worker_move_time = 10;</code>
   * @return The workerMoveTime.
   */
  @java.lang.Override
  public int getWorkerMoveTime() {
    return workerMoveTime_;
  }

  public static final int WORKER_HARVEST_TIME_FIELD_NUMBER = 11;
  private int workerHarvestTime_;
  /**
   * <code>int32 worker_harvest_time = 11;</code>
   * @return The workerHarvestTime.
   */
  @java.lang.Override
  public int getWorkerHarvestTime() {
    return workerHarvestTime_;
  }

  public static final int WORKER_RETURN_TIME_FIELD_NUMBER = 12;
  private int workerReturnTime_;
  /**
   * <code>int32 worker_return_time = 12;</code>
   * @return The workerReturnTime.
   */
  @java.lang.Override
  public int getWorkerReturnTime() {
    return workerReturnTime_;
  }

  public static final int HARVEST_AMOUNT_FIELD_NUMBER = 13;
  private int harvestAmount_;
  /**
   * <code>int32 harvest_amount = 13;</code>
   * @return The harvestAmount.
   */
  @java.lang.Override
  public int getHarvestAmount() {
    return harvestAmount_;
  }

  public static final int BASE_COST_FIELD_NUMBER = 14;
  private int baseCost_;
  /**
   * <code>int32 base_cost = 14;</code>
   * @return The baseCost.
   */
  @java.lang.Override
  public int getBaseCost() {
    return baseCost_;
  }

  public static final int BARRACKS_COST_FIELD_NUMBER = 15;
  private int barracksCost_;
  /**
   * <code>int32 barracks_cost = 15;</code>
   * @return The barracksCost.
   */
  @java.lang.Override
  public int getBarracksCost() {
    return barracksCost_;
  }

  public static final int HEAVY_COST_FIELD_NUMBER = 16;
  private int heavyCost_;
  /**
   * <code>int32 heavy_cost = 16;</code>
   * @return The heavyCost.
   */
  @java.lang.Override
  public int getHeavyCost() {
    return heavyCost_;
  }

  public static final int LIGHT_COST_FIELD_NUMBER = 17;
  private int lightCost_;
  /**
   * <code>int32 light_cost = 17;</code>
   * @return The lightCost.
   */
  @java.lang.Override
  public int getLightCost() {
    return lightCost_;
  }

  public static final int RANGED_COST_FIELD_NUMBER = 18;
  private int rangedCost_;
  /**
   * <code>int32 ranged_cost = 18;</code>
   * @return The rangedCost.
   */
  @java.lang.Override
  public int getRangedCost() {
    return rangedCost_;
  }

  public static final int MY_HEAVY_UNITS_FIELD_NUMBER = 19;
  private int myHeavyUnits_;
  /**
   * <code>int32 my_heavy_units = 19;</code>
   * @return The myHeavyUnits.
   */
  @java.lang.Override
  public int getMyHeavyUnits() {
    return myHeavyUnits_;
  }

  public static final int MY_LIGHT_UNITS_FIELD_NUMBER = 20;
  private int myLightUnits_;
  /**
   * <code>int32 my_light_units = 20;</code>
   * @return The myLightUnits.
   */
  @java.lang.Override
  public int getMyLightUnits() {
    return myLightUnits_;
  }

  public static final int MY_RANGED_UNITS_FIELD_NUMBER = 21;
  private int myRangedUnits_;
  /**
   * <code>int32 my_ranged_units = 21;</code>
   * @return The myRangedUnits.
   */
  @java.lang.Override
  public int getMyRangedUnits() {
    return myRangedUnits_;
  }

  public static final int INITIAL_ENEMY_WORKER_FIELD_NUMBER = 22;
  private int initialEnemyWorker_;
  /**
   * <code>int32 initial_enemy_worker = 22;</code>
   * @return The initialEnemyWorker.
   */
  @java.lang.Override
  public int getInitialEnemyWorker() {
    return initialEnemyWorker_;
  }

  public static final int OBSERVED_ENEMY_WORKER_FIELD_NUMBER = 23;
  private int observedEnemyWorker_;
  /**
   * <code>int32 observed_enemy_worker = 23;</code>
   * @return The observedEnemyWorker.
   */
  @java.lang.Override
  public int getObservedEnemyWorker() {
    return observedEnemyWorker_;
  }

  public static final int OBSERVED_ENEMY_HEAVY_FIELD_NUMBER = 24;
  private int observedEnemyHeavy_;
  /**
   * <code>int32 observed_enemy_heavy = 24;</code>
   * @return The observedEnemyHeavy.
   */
  @java.lang.Override
  public int getObservedEnemyHeavy() {
    return observedEnemyHeavy_;
  }

  public static final int OBSERVED_ENEMY_LIGHT_FIELD_NUMBER = 25;
  private int observedEnemyLight_;
  /**
   * <code>int32 observed_enemy_light = 25;</code>
   * @return The observedEnemyLight.
   */
  @java.lang.Override
  public int getObservedEnemyLight() {
    return observedEnemyLight_;
  }

  public static final int OBSERVED_ENEMY_RANGED_FIELD_NUMBER = 26;
  private int observedEnemyRanged_;
  /**
   * <code>int32 observed_enemy_ranged = 26;</code>
   * @return The observedEnemyRanged.
   */
  @java.lang.Override
  public int getObservedEnemyRanged() {
    return observedEnemyRanged_;
  }

  public static final int OBSERVED_ENEMY_WORKER_IN_TOTAL_FIELD_NUMBER = 27;
  private int observedEnemyWorkerInTotal_;
  /**
   * <code>int32 observed_enemy_worker_in_total = 27;</code>
   * @return The observedEnemyWorkerInTotal.
   */
  @java.lang.Override
  public int getObservedEnemyWorkerInTotal() {
    return observedEnemyWorkerInTotal_;
  }

  public static final int OBSERVED_ENEMY_HEAVY_IN_TOTAL_FIELD_NUMBER = 28;
  private int observedEnemyHeavyInTotal_;
  /**
   * <code>int32 observed_enemy_heavy_in_total = 28;</code>
   * @return The observedEnemyHeavyInTotal.
   */
  @java.lang.Override
  public int getObservedEnemyHeavyInTotal() {
    return observedEnemyHeavyInTotal_;
  }

  public static final int OBSERVED_ENEMY_LIGHT_IN_TOTAL_FIELD_NUMBER = 29;
  private int observedEnemyLightInTotal_;
  /**
   * <code>int32 observed_enemy_light_in_total = 29;</code>
   * @return The observedEnemyLightInTotal.
   */
  @java.lang.Override
  public int getObservedEnemyLightInTotal() {
    return observedEnemyLightInTotal_;
  }

  public static final int OBSERVED_ENEMY_RANGED_IN_TOTAL_FIELD_NUMBER = 30;
  private int observedEnemyRangedInTotal_;
  /**
   * <code>int32 observed_enemy_ranged_in_total = 30;</code>
   * @return The observedEnemyRangedInTotal.
   */
  @java.lang.Override
  public int getObservedEnemyRangedInTotal() {
    return observedEnemyRangedInTotal_;
  }

  public static final int SOLVER_TYPE_FIELD_NUMBER = 31;
  private int solverType_;
  /**
   * <code>int32 solver_type = 31;</code>
   * @return The solverType.
   */
  @java.lang.Override
  public int getSolverType() {
    return solverType_;
  }

  public static final int NB_SAMPLES_FIELD_NUMBER = 32;
  private int nbSamples_;
  /**
   * <code>int32 nb_samples = 32;</code>
   * @return The nbSamples.
   */
  @java.lang.Override
  public int getNbSamples() {
    return nbSamples_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (time_ != 0) {
      output.writeInt32(1, time_);
    }
    if (nbBarracks_ != 0) {
      output.writeInt32(2, nbBarracks_);
    }
    if (minDistanceResourceBase_ != 0) {
      output.writeInt32(3, minDistanceResourceBase_);
    }
    if (maxDistanceResourceBase_ != 0) {
      output.writeInt32(4, maxDistanceResourceBase_);
    }
    if (noInitialBase_ != 0) {
      output.writeInt32(5, noInitialBase_);
    }
    if (noInitialBarracks_ != 0) {
      output.writeInt32(6, noInitialBarracks_);
    }
    if (resources_ != 0) {
      output.writeInt32(7, resources_);
    }
    if (initialResources_ != 0) {
      output.writeInt32(8, initialResources_);
    }
    if (enemyResourcesLoss_ != 0) {
      output.writeInt32(9, enemyResourcesLoss_);
    }
    if (workerMoveTime_ != 0) {
      output.writeInt32(10, workerMoveTime_);
    }
    if (workerHarvestTime_ != 0) {
      output.writeInt32(11, workerHarvestTime_);
    }
    if (workerReturnTime_ != 0) {
      output.writeInt32(12, workerReturnTime_);
    }
    if (harvestAmount_ != 0) {
      output.writeInt32(13, harvestAmount_);
    }
    if (baseCost_ != 0) {
      output.writeInt32(14, baseCost_);
    }
    if (barracksCost_ != 0) {
      output.writeInt32(15, barracksCost_);
    }
    if (heavyCost_ != 0) {
      output.writeInt32(16, heavyCost_);
    }
    if (lightCost_ != 0) {
      output.writeInt32(17, lightCost_);
    }
    if (rangedCost_ != 0) {
      output.writeInt32(18, rangedCost_);
    }
    if (myHeavyUnits_ != 0) {
      output.writeInt32(19, myHeavyUnits_);
    }
    if (myLightUnits_ != 0) {
      output.writeInt32(20, myLightUnits_);
    }
    if (myRangedUnits_ != 0) {
      output.writeInt32(21, myRangedUnits_);
    }
    if (initialEnemyWorker_ != 0) {
      output.writeInt32(22, initialEnemyWorker_);
    }
    if (observedEnemyWorker_ != 0) {
      output.writeInt32(23, observedEnemyWorker_);
    }
    if (observedEnemyHeavy_ != 0) {
      output.writeInt32(24, observedEnemyHeavy_);
    }
    if (observedEnemyLight_ != 0) {
      output.writeInt32(25, observedEnemyLight_);
    }
    if (observedEnemyRanged_ != 0) {
      output.writeInt32(26, observedEnemyRanged_);
    }
    if (observedEnemyWorkerInTotal_ != 0) {
      output.writeInt32(27, observedEnemyWorkerInTotal_);
    }
    if (observedEnemyHeavyInTotal_ != 0) {
      output.writeInt32(28, observedEnemyHeavyInTotal_);
    }
    if (observedEnemyLightInTotal_ != 0) {
      output.writeInt32(29, observedEnemyLightInTotal_);
    }
    if (observedEnemyRangedInTotal_ != 0) {
      output.writeInt32(30, observedEnemyRangedInTotal_);
    }
    if (solverType_ != 0) {
      output.writeInt32(31, solverType_);
    }
    if (nbSamples_ != 0) {
      output.writeInt32(32, nbSamples_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (time_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, time_);
    }
    if (nbBarracks_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, nbBarracks_);
    }
    if (minDistanceResourceBase_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, minDistanceResourceBase_);
    }
    if (maxDistanceResourceBase_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, maxDistanceResourceBase_);
    }
    if (noInitialBase_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, noInitialBase_);
    }
    if (noInitialBarracks_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, noInitialBarracks_);
    }
    if (resources_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, resources_);
    }
    if (initialResources_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, initialResources_);
    }
    if (enemyResourcesLoss_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, enemyResourcesLoss_);
    }
    if (workerMoveTime_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, workerMoveTime_);
    }
    if (workerHarvestTime_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, workerHarvestTime_);
    }
    if (workerReturnTime_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(12, workerReturnTime_);
    }
    if (harvestAmount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(13, harvestAmount_);
    }
    if (baseCost_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(14, baseCost_);
    }
    if (barracksCost_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(15, barracksCost_);
    }
    if (heavyCost_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(16, heavyCost_);
    }
    if (lightCost_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(17, lightCost_);
    }
    if (rangedCost_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(18, rangedCost_);
    }
    if (myHeavyUnits_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(19, myHeavyUnits_);
    }
    if (myLightUnits_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(20, myLightUnits_);
    }
    if (myRangedUnits_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(21, myRangedUnits_);
    }
    if (initialEnemyWorker_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(22, initialEnemyWorker_);
    }
    if (observedEnemyWorker_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(23, observedEnemyWorker_);
    }
    if (observedEnemyHeavy_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(24, observedEnemyHeavy_);
    }
    if (observedEnemyLight_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(25, observedEnemyLight_);
    }
    if (observedEnemyRanged_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(26, observedEnemyRanged_);
    }
    if (observedEnemyWorkerInTotal_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(27, observedEnemyWorkerInTotal_);
    }
    if (observedEnemyHeavyInTotal_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(28, observedEnemyHeavyInTotal_);
    }
    if (observedEnemyLightInTotal_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(29, observedEnemyLightInTotal_);
    }
    if (observedEnemyRangedInTotal_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(30, observedEnemyRangedInTotal_);
    }
    if (solverType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(31, solverType_);
    }
    if (nbSamples_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(32, nbSamples_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.microphantom.protos.GameStateBuffer)) {
      return super.equals(obj);
    }
    com.microphantom.protos.GameStateBuffer other = (com.microphantom.protos.GameStateBuffer) obj;

    if (getTime()
        != other.getTime()) return false;
    if (getNbBarracks()
        != other.getNbBarracks()) return false;
    if (getMinDistanceResourceBase()
        != other.getMinDistanceResourceBase()) return false;
    if (getMaxDistanceResourceBase()
        != other.getMaxDistanceResourceBase()) return false;
    if (getNoInitialBase()
        != other.getNoInitialBase()) return false;
    if (getNoInitialBarracks()
        != other.getNoInitialBarracks()) return false;
    if (getResources()
        != other.getResources()) return false;
    if (getInitialResources()
        != other.getInitialResources()) return false;
    if (getEnemyResourcesLoss()
        != other.getEnemyResourcesLoss()) return false;
    if (getWorkerMoveTime()
        != other.getWorkerMoveTime()) return false;
    if (getWorkerHarvestTime()
        != other.getWorkerHarvestTime()) return false;
    if (getWorkerReturnTime()
        != other.getWorkerReturnTime()) return false;
    if (getHarvestAmount()
        != other.getHarvestAmount()) return false;
    if (getBaseCost()
        != other.getBaseCost()) return false;
    if (getBarracksCost()
        != other.getBarracksCost()) return false;
    if (getHeavyCost()
        != other.getHeavyCost()) return false;
    if (getLightCost()
        != other.getLightCost()) return false;
    if (getRangedCost()
        != other.getRangedCost()) return false;
    if (getMyHeavyUnits()
        != other.getMyHeavyUnits()) return false;
    if (getMyLightUnits()
        != other.getMyLightUnits()) return false;
    if (getMyRangedUnits()
        != other.getMyRangedUnits()) return false;
    if (getInitialEnemyWorker()
        != other.getInitialEnemyWorker()) return false;
    if (getObservedEnemyWorker()
        != other.getObservedEnemyWorker()) return false;
    if (getObservedEnemyHeavy()
        != other.getObservedEnemyHeavy()) return false;
    if (getObservedEnemyLight()
        != other.getObservedEnemyLight()) return false;
    if (getObservedEnemyRanged()
        != other.getObservedEnemyRanged()) return false;
    if (getObservedEnemyWorkerInTotal()
        != other.getObservedEnemyWorkerInTotal()) return false;
    if (getObservedEnemyHeavyInTotal()
        != other.getObservedEnemyHeavyInTotal()) return false;
    if (getObservedEnemyLightInTotal()
        != other.getObservedEnemyLightInTotal()) return false;
    if (getObservedEnemyRangedInTotal()
        != other.getObservedEnemyRangedInTotal()) return false;
    if (getSolverType()
        != other.getSolverType()) return false;
    if (getNbSamples()
        != other.getNbSamples()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIME_FIELD_NUMBER;
    hash = (53 * hash) + getTime();
    hash = (37 * hash) + NB_BARRACKS_FIELD_NUMBER;
    hash = (53 * hash) + getNbBarracks();
    hash = (37 * hash) + MIN_DISTANCE_RESOURCE_BASE_FIELD_NUMBER;
    hash = (53 * hash) + getMinDistanceResourceBase();
    hash = (37 * hash) + MAX_DISTANCE_RESOURCE_BASE_FIELD_NUMBER;
    hash = (53 * hash) + getMaxDistanceResourceBase();
    hash = (37 * hash) + NO_INITIAL_BASE_FIELD_NUMBER;
    hash = (53 * hash) + getNoInitialBase();
    hash = (37 * hash) + NO_INITIAL_BARRACKS_FIELD_NUMBER;
    hash = (53 * hash) + getNoInitialBarracks();
    hash = (37 * hash) + RESOURCES_FIELD_NUMBER;
    hash = (53 * hash) + getResources();
    hash = (37 * hash) + INITIAL_RESOURCES_FIELD_NUMBER;
    hash = (53 * hash) + getInitialResources();
    hash = (37 * hash) + ENEMY_RESOURCES_LOSS_FIELD_NUMBER;
    hash = (53 * hash) + getEnemyResourcesLoss();
    hash = (37 * hash) + WORKER_MOVE_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getWorkerMoveTime();
    hash = (37 * hash) + WORKER_HARVEST_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getWorkerHarvestTime();
    hash = (37 * hash) + WORKER_RETURN_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getWorkerReturnTime();
    hash = (37 * hash) + HARVEST_AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getHarvestAmount();
    hash = (37 * hash) + BASE_COST_FIELD_NUMBER;
    hash = (53 * hash) + getBaseCost();
    hash = (37 * hash) + BARRACKS_COST_FIELD_NUMBER;
    hash = (53 * hash) + getBarracksCost();
    hash = (37 * hash) + HEAVY_COST_FIELD_NUMBER;
    hash = (53 * hash) + getHeavyCost();
    hash = (37 * hash) + LIGHT_COST_FIELD_NUMBER;
    hash = (53 * hash) + getLightCost();
    hash = (37 * hash) + RANGED_COST_FIELD_NUMBER;
    hash = (53 * hash) + getRangedCost();
    hash = (37 * hash) + MY_HEAVY_UNITS_FIELD_NUMBER;
    hash = (53 * hash) + getMyHeavyUnits();
    hash = (37 * hash) + MY_LIGHT_UNITS_FIELD_NUMBER;
    hash = (53 * hash) + getMyLightUnits();
    hash = (37 * hash) + MY_RANGED_UNITS_FIELD_NUMBER;
    hash = (53 * hash) + getMyRangedUnits();
    hash = (37 * hash) + INITIAL_ENEMY_WORKER_FIELD_NUMBER;
    hash = (53 * hash) + getInitialEnemyWorker();
    hash = (37 * hash) + OBSERVED_ENEMY_WORKER_FIELD_NUMBER;
    hash = (53 * hash) + getObservedEnemyWorker();
    hash = (37 * hash) + OBSERVED_ENEMY_HEAVY_FIELD_NUMBER;
    hash = (53 * hash) + getObservedEnemyHeavy();
    hash = (37 * hash) + OBSERVED_ENEMY_LIGHT_FIELD_NUMBER;
    hash = (53 * hash) + getObservedEnemyLight();
    hash = (37 * hash) + OBSERVED_ENEMY_RANGED_FIELD_NUMBER;
    hash = (53 * hash) + getObservedEnemyRanged();
    hash = (37 * hash) + OBSERVED_ENEMY_WORKER_IN_TOTAL_FIELD_NUMBER;
    hash = (53 * hash) + getObservedEnemyWorkerInTotal();
    hash = (37 * hash) + OBSERVED_ENEMY_HEAVY_IN_TOTAL_FIELD_NUMBER;
    hash = (53 * hash) + getObservedEnemyHeavyInTotal();
    hash = (37 * hash) + OBSERVED_ENEMY_LIGHT_IN_TOTAL_FIELD_NUMBER;
    hash = (53 * hash) + getObservedEnemyLightInTotal();
    hash = (37 * hash) + OBSERVED_ENEMY_RANGED_IN_TOTAL_FIELD_NUMBER;
    hash = (53 * hash) + getObservedEnemyRangedInTotal();
    hash = (37 * hash) + SOLVER_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getSolverType();
    hash = (37 * hash) + NB_SAMPLES_FIELD_NUMBER;
    hash = (53 * hash) + getNbSamples();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.microphantom.protos.GameStateBuffer parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.microphantom.protos.GameStateBuffer parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.microphantom.protos.GameStateBuffer parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.microphantom.protos.GameStateBuffer parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.microphantom.protos.GameStateBuffer parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.microphantom.protos.GameStateBuffer parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.microphantom.protos.GameStateBuffer parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.microphantom.protos.GameStateBuffer parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.microphantom.protos.GameStateBuffer parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.microphantom.protos.GameStateBuffer parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.microphantom.protos.GameStateBuffer parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.microphantom.protos.GameStateBuffer parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.microphantom.protos.GameStateBuffer prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GameStateBuffer}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GameStateBuffer)
      com.microphantom.protos.GameStateBufferOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.microphantom.protos.MicroPhantomProtos.internal_static_GameStateBuffer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.microphantom.protos.MicroPhantomProtos.internal_static_GameStateBuffer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.microphantom.protos.GameStateBuffer.class, com.microphantom.protos.GameStateBuffer.Builder.class);
    }

    // Construct using com.microphantom.protos.GameStateBuffer.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      time_ = 0;

      nbBarracks_ = 0;

      minDistanceResourceBase_ = 0;

      maxDistanceResourceBase_ = 0;

      noInitialBase_ = 0;

      noInitialBarracks_ = 0;

      resources_ = 0;

      initialResources_ = 0;

      enemyResourcesLoss_ = 0;

      workerMoveTime_ = 0;

      workerHarvestTime_ = 0;

      workerReturnTime_ = 0;

      harvestAmount_ = 0;

      baseCost_ = 0;

      barracksCost_ = 0;

      heavyCost_ = 0;

      lightCost_ = 0;

      rangedCost_ = 0;

      myHeavyUnits_ = 0;

      myLightUnits_ = 0;

      myRangedUnits_ = 0;

      initialEnemyWorker_ = 0;

      observedEnemyWorker_ = 0;

      observedEnemyHeavy_ = 0;

      observedEnemyLight_ = 0;

      observedEnemyRanged_ = 0;

      observedEnemyWorkerInTotal_ = 0;

      observedEnemyHeavyInTotal_ = 0;

      observedEnemyLightInTotal_ = 0;

      observedEnemyRangedInTotal_ = 0;

      solverType_ = 0;

      nbSamples_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.microphantom.protos.MicroPhantomProtos.internal_static_GameStateBuffer_descriptor;
    }

    @java.lang.Override
    public com.microphantom.protos.GameStateBuffer getDefaultInstanceForType() {
      return com.microphantom.protos.GameStateBuffer.getDefaultInstance();
    }

    @java.lang.Override
    public com.microphantom.protos.GameStateBuffer build() {
      com.microphantom.protos.GameStateBuffer result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.microphantom.protos.GameStateBuffer buildPartial() {
      com.microphantom.protos.GameStateBuffer result = new com.microphantom.protos.GameStateBuffer(this);
      result.time_ = time_;
      result.nbBarracks_ = nbBarracks_;
      result.minDistanceResourceBase_ = minDistanceResourceBase_;
      result.maxDistanceResourceBase_ = maxDistanceResourceBase_;
      result.noInitialBase_ = noInitialBase_;
      result.noInitialBarracks_ = noInitialBarracks_;
      result.resources_ = resources_;
      result.initialResources_ = initialResources_;
      result.enemyResourcesLoss_ = enemyResourcesLoss_;
      result.workerMoveTime_ = workerMoveTime_;
      result.workerHarvestTime_ = workerHarvestTime_;
      result.workerReturnTime_ = workerReturnTime_;
      result.harvestAmount_ = harvestAmount_;
      result.baseCost_ = baseCost_;
      result.barracksCost_ = barracksCost_;
      result.heavyCost_ = heavyCost_;
      result.lightCost_ = lightCost_;
      result.rangedCost_ = rangedCost_;
      result.myHeavyUnits_ = myHeavyUnits_;
      result.myLightUnits_ = myLightUnits_;
      result.myRangedUnits_ = myRangedUnits_;
      result.initialEnemyWorker_ = initialEnemyWorker_;
      result.observedEnemyWorker_ = observedEnemyWorker_;
      result.observedEnemyHeavy_ = observedEnemyHeavy_;
      result.observedEnemyLight_ = observedEnemyLight_;
      result.observedEnemyRanged_ = observedEnemyRanged_;
      result.observedEnemyWorkerInTotal_ = observedEnemyWorkerInTotal_;
      result.observedEnemyHeavyInTotal_ = observedEnemyHeavyInTotal_;
      result.observedEnemyLightInTotal_ = observedEnemyLightInTotal_;
      result.observedEnemyRangedInTotal_ = observedEnemyRangedInTotal_;
      result.solverType_ = solverType_;
      result.nbSamples_ = nbSamples_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.microphantom.protos.GameStateBuffer) {
        return mergeFrom((com.microphantom.protos.GameStateBuffer)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.microphantom.protos.GameStateBuffer other) {
      if (other == com.microphantom.protos.GameStateBuffer.getDefaultInstance()) return this;
      if (other.getTime() != 0) {
        setTime(other.getTime());
      }
      if (other.getNbBarracks() != 0) {
        setNbBarracks(other.getNbBarracks());
      }
      if (other.getMinDistanceResourceBase() != 0) {
        setMinDistanceResourceBase(other.getMinDistanceResourceBase());
      }
      if (other.getMaxDistanceResourceBase() != 0) {
        setMaxDistanceResourceBase(other.getMaxDistanceResourceBase());
      }
      if (other.getNoInitialBase() != 0) {
        setNoInitialBase(other.getNoInitialBase());
      }
      if (other.getNoInitialBarracks() != 0) {
        setNoInitialBarracks(other.getNoInitialBarracks());
      }
      if (other.getResources() != 0) {
        setResources(other.getResources());
      }
      if (other.getInitialResources() != 0) {
        setInitialResources(other.getInitialResources());
      }
      if (other.getEnemyResourcesLoss() != 0) {
        setEnemyResourcesLoss(other.getEnemyResourcesLoss());
      }
      if (other.getWorkerMoveTime() != 0) {
        setWorkerMoveTime(other.getWorkerMoveTime());
      }
      if (other.getWorkerHarvestTime() != 0) {
        setWorkerHarvestTime(other.getWorkerHarvestTime());
      }
      if (other.getWorkerReturnTime() != 0) {
        setWorkerReturnTime(other.getWorkerReturnTime());
      }
      if (other.getHarvestAmount() != 0) {
        setHarvestAmount(other.getHarvestAmount());
      }
      if (other.getBaseCost() != 0) {
        setBaseCost(other.getBaseCost());
      }
      if (other.getBarracksCost() != 0) {
        setBarracksCost(other.getBarracksCost());
      }
      if (other.getHeavyCost() != 0) {
        setHeavyCost(other.getHeavyCost());
      }
      if (other.getLightCost() != 0) {
        setLightCost(other.getLightCost());
      }
      if (other.getRangedCost() != 0) {
        setRangedCost(other.getRangedCost());
      }
      if (other.getMyHeavyUnits() != 0) {
        setMyHeavyUnits(other.getMyHeavyUnits());
      }
      if (other.getMyLightUnits() != 0) {
        setMyLightUnits(other.getMyLightUnits());
      }
      if (other.getMyRangedUnits() != 0) {
        setMyRangedUnits(other.getMyRangedUnits());
      }
      if (other.getInitialEnemyWorker() != 0) {
        setInitialEnemyWorker(other.getInitialEnemyWorker());
      }
      if (other.getObservedEnemyWorker() != 0) {
        setObservedEnemyWorker(other.getObservedEnemyWorker());
      }
      if (other.getObservedEnemyHeavy() != 0) {
        setObservedEnemyHeavy(other.getObservedEnemyHeavy());
      }
      if (other.getObservedEnemyLight() != 0) {
        setObservedEnemyLight(other.getObservedEnemyLight());
      }
      if (other.getObservedEnemyRanged() != 0) {
        setObservedEnemyRanged(other.getObservedEnemyRanged());
      }
      if (other.getObservedEnemyWorkerInTotal() != 0) {
        setObservedEnemyWorkerInTotal(other.getObservedEnemyWorkerInTotal());
      }
      if (other.getObservedEnemyHeavyInTotal() != 0) {
        setObservedEnemyHeavyInTotal(other.getObservedEnemyHeavyInTotal());
      }
      if (other.getObservedEnemyLightInTotal() != 0) {
        setObservedEnemyLightInTotal(other.getObservedEnemyLightInTotal());
      }
      if (other.getObservedEnemyRangedInTotal() != 0) {
        setObservedEnemyRangedInTotal(other.getObservedEnemyRangedInTotal());
      }
      if (other.getSolverType() != 0) {
        setSolverType(other.getSolverType());
      }
      if (other.getNbSamples() != 0) {
        setNbSamples(other.getNbSamples());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.microphantom.protos.GameStateBuffer parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.microphantom.protos.GameStateBuffer) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int time_ ;
    /**
     * <code>int32 time = 1;</code>
     * @return The time.
     */
    @java.lang.Override
    public int getTime() {
      return time_;
    }
    /**
     * <code>int32 time = 1;</code>
     * @param value The time to set.
     * @return This builder for chaining.
     */
    public Builder setTime(int value) {
      
      time_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 time = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTime() {
      
      time_ = 0;
      onChanged();
      return this;
    }

    private int nbBarracks_ ;
    /**
     * <code>int32 nb_barracks = 2;</code>
     * @return The nbBarracks.
     */
    @java.lang.Override
    public int getNbBarracks() {
      return nbBarracks_;
    }
    /**
     * <code>int32 nb_barracks = 2;</code>
     * @param value The nbBarracks to set.
     * @return This builder for chaining.
     */
    public Builder setNbBarracks(int value) {
      
      nbBarracks_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 nb_barracks = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNbBarracks() {
      
      nbBarracks_ = 0;
      onChanged();
      return this;
    }

    private int minDistanceResourceBase_ ;
    /**
     * <code>int32 min_distance_resource_base = 3;</code>
     * @return The minDistanceResourceBase.
     */
    @java.lang.Override
    public int getMinDistanceResourceBase() {
      return minDistanceResourceBase_;
    }
    /**
     * <code>int32 min_distance_resource_base = 3;</code>
     * @param value The minDistanceResourceBase to set.
     * @return This builder for chaining.
     */
    public Builder setMinDistanceResourceBase(int value) {
      
      minDistanceResourceBase_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 min_distance_resource_base = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinDistanceResourceBase() {
      
      minDistanceResourceBase_ = 0;
      onChanged();
      return this;
    }

    private int maxDistanceResourceBase_ ;
    /**
     * <code>int32 max_distance_resource_base = 4;</code>
     * @return The maxDistanceResourceBase.
     */
    @java.lang.Override
    public int getMaxDistanceResourceBase() {
      return maxDistanceResourceBase_;
    }
    /**
     * <code>int32 max_distance_resource_base = 4;</code>
     * @param value The maxDistanceResourceBase to set.
     * @return This builder for chaining.
     */
    public Builder setMaxDistanceResourceBase(int value) {
      
      maxDistanceResourceBase_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 max_distance_resource_base = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxDistanceResourceBase() {
      
      maxDistanceResourceBase_ = 0;
      onChanged();
      return this;
    }

    private int noInitialBase_ ;
    /**
     * <code>int32 no_initial_base = 5;</code>
     * @return The noInitialBase.
     */
    @java.lang.Override
    public int getNoInitialBase() {
      return noInitialBase_;
    }
    /**
     * <code>int32 no_initial_base = 5;</code>
     * @param value The noInitialBase to set.
     * @return This builder for chaining.
     */
    public Builder setNoInitialBase(int value) {
      
      noInitialBase_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 no_initial_base = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearNoInitialBase() {
      
      noInitialBase_ = 0;
      onChanged();
      return this;
    }

    private int noInitialBarracks_ ;
    /**
     * <code>int32 no_initial_barracks = 6;</code>
     * @return The noInitialBarracks.
     */
    @java.lang.Override
    public int getNoInitialBarracks() {
      return noInitialBarracks_;
    }
    /**
     * <code>int32 no_initial_barracks = 6;</code>
     * @param value The noInitialBarracks to set.
     * @return This builder for chaining.
     */
    public Builder setNoInitialBarracks(int value) {
      
      noInitialBarracks_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 no_initial_barracks = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearNoInitialBarracks() {
      
      noInitialBarracks_ = 0;
      onChanged();
      return this;
    }

    private int resources_ ;
    /**
     * <code>int32 resources = 7;</code>
     * @return The resources.
     */
    @java.lang.Override
    public int getResources() {
      return resources_;
    }
    /**
     * <code>int32 resources = 7;</code>
     * @param value The resources to set.
     * @return This builder for chaining.
     */
    public Builder setResources(int value) {
      
      resources_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 resources = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearResources() {
      
      resources_ = 0;
      onChanged();
      return this;
    }

    private int initialResources_ ;
    /**
     * <code>int32 initial_resources = 8;</code>
     * @return The initialResources.
     */
    @java.lang.Override
    public int getInitialResources() {
      return initialResources_;
    }
    /**
     * <code>int32 initial_resources = 8;</code>
     * @param value The initialResources to set.
     * @return This builder for chaining.
     */
    public Builder setInitialResources(int value) {
      
      initialResources_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 initial_resources = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearInitialResources() {
      
      initialResources_ = 0;
      onChanged();
      return this;
    }

    private int enemyResourcesLoss_ ;
    /**
     * <code>int32 enemy_resources_loss = 9;</code>
     * @return The enemyResourcesLoss.
     */
    @java.lang.Override
    public int getEnemyResourcesLoss() {
      return enemyResourcesLoss_;
    }
    /**
     * <code>int32 enemy_resources_loss = 9;</code>
     * @param value The enemyResourcesLoss to set.
     * @return This builder for chaining.
     */
    public Builder setEnemyResourcesLoss(int value) {
      
      enemyResourcesLoss_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 enemy_resources_loss = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnemyResourcesLoss() {
      
      enemyResourcesLoss_ = 0;
      onChanged();
      return this;
    }

    private int workerMoveTime_ ;
    /**
     * <code>int32 worker_move_time = 10;</code>
     * @return The workerMoveTime.
     */
    @java.lang.Override
    public int getWorkerMoveTime() {
      return workerMoveTime_;
    }
    /**
     * <code>int32 worker_move_time = 10;</code>
     * @param value The workerMoveTime to set.
     * @return This builder for chaining.
     */
    public Builder setWorkerMoveTime(int value) {
      
      workerMoveTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 worker_move_time = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearWorkerMoveTime() {
      
      workerMoveTime_ = 0;
      onChanged();
      return this;
    }

    private int workerHarvestTime_ ;
    /**
     * <code>int32 worker_harvest_time = 11;</code>
     * @return The workerHarvestTime.
     */
    @java.lang.Override
    public int getWorkerHarvestTime() {
      return workerHarvestTime_;
    }
    /**
     * <code>int32 worker_harvest_time = 11;</code>
     * @param value The workerHarvestTime to set.
     * @return This builder for chaining.
     */
    public Builder setWorkerHarvestTime(int value) {
      
      workerHarvestTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 worker_harvest_time = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearWorkerHarvestTime() {
      
      workerHarvestTime_ = 0;
      onChanged();
      return this;
    }

    private int workerReturnTime_ ;
    /**
     * <code>int32 worker_return_time = 12;</code>
     * @return The workerReturnTime.
     */
    @java.lang.Override
    public int getWorkerReturnTime() {
      return workerReturnTime_;
    }
    /**
     * <code>int32 worker_return_time = 12;</code>
     * @param value The workerReturnTime to set.
     * @return This builder for chaining.
     */
    public Builder setWorkerReturnTime(int value) {
      
      workerReturnTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 worker_return_time = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearWorkerReturnTime() {
      
      workerReturnTime_ = 0;
      onChanged();
      return this;
    }

    private int harvestAmount_ ;
    /**
     * <code>int32 harvest_amount = 13;</code>
     * @return The harvestAmount.
     */
    @java.lang.Override
    public int getHarvestAmount() {
      return harvestAmount_;
    }
    /**
     * <code>int32 harvest_amount = 13;</code>
     * @param value The harvestAmount to set.
     * @return This builder for chaining.
     */
    public Builder setHarvestAmount(int value) {
      
      harvestAmount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 harvest_amount = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearHarvestAmount() {
      
      harvestAmount_ = 0;
      onChanged();
      return this;
    }

    private int baseCost_ ;
    /**
     * <code>int32 base_cost = 14;</code>
     * @return The baseCost.
     */
    @java.lang.Override
    public int getBaseCost() {
      return baseCost_;
    }
    /**
     * <code>int32 base_cost = 14;</code>
     * @param value The baseCost to set.
     * @return This builder for chaining.
     */
    public Builder setBaseCost(int value) {
      
      baseCost_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 base_cost = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearBaseCost() {
      
      baseCost_ = 0;
      onChanged();
      return this;
    }

    private int barracksCost_ ;
    /**
     * <code>int32 barracks_cost = 15;</code>
     * @return The barracksCost.
     */
    @java.lang.Override
    public int getBarracksCost() {
      return barracksCost_;
    }
    /**
     * <code>int32 barracks_cost = 15;</code>
     * @param value The barracksCost to set.
     * @return This builder for chaining.
     */
    public Builder setBarracksCost(int value) {
      
      barracksCost_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 barracks_cost = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearBarracksCost() {
      
      barracksCost_ = 0;
      onChanged();
      return this;
    }

    private int heavyCost_ ;
    /**
     * <code>int32 heavy_cost = 16;</code>
     * @return The heavyCost.
     */
    @java.lang.Override
    public int getHeavyCost() {
      return heavyCost_;
    }
    /**
     * <code>int32 heavy_cost = 16;</code>
     * @param value The heavyCost to set.
     * @return This builder for chaining.
     */
    public Builder setHeavyCost(int value) {
      
      heavyCost_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 heavy_cost = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearHeavyCost() {
      
      heavyCost_ = 0;
      onChanged();
      return this;
    }

    private int lightCost_ ;
    /**
     * <code>int32 light_cost = 17;</code>
     * @return The lightCost.
     */
    @java.lang.Override
    public int getLightCost() {
      return lightCost_;
    }
    /**
     * <code>int32 light_cost = 17;</code>
     * @param value The lightCost to set.
     * @return This builder for chaining.
     */
    public Builder setLightCost(int value) {
      
      lightCost_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 light_cost = 17;</code>
     * @return This builder for chaining.
     */
    public Builder clearLightCost() {
      
      lightCost_ = 0;
      onChanged();
      return this;
    }

    private int rangedCost_ ;
    /**
     * <code>int32 ranged_cost = 18;</code>
     * @return The rangedCost.
     */
    @java.lang.Override
    public int getRangedCost() {
      return rangedCost_;
    }
    /**
     * <code>int32 ranged_cost = 18;</code>
     * @param value The rangedCost to set.
     * @return This builder for chaining.
     */
    public Builder setRangedCost(int value) {
      
      rangedCost_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 ranged_cost = 18;</code>
     * @return This builder for chaining.
     */
    public Builder clearRangedCost() {
      
      rangedCost_ = 0;
      onChanged();
      return this;
    }

    private int myHeavyUnits_ ;
    /**
     * <code>int32 my_heavy_units = 19;</code>
     * @return The myHeavyUnits.
     */
    @java.lang.Override
    public int getMyHeavyUnits() {
      return myHeavyUnits_;
    }
    /**
     * <code>int32 my_heavy_units = 19;</code>
     * @param value The myHeavyUnits to set.
     * @return This builder for chaining.
     */
    public Builder setMyHeavyUnits(int value) {
      
      myHeavyUnits_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 my_heavy_units = 19;</code>
     * @return This builder for chaining.
     */
    public Builder clearMyHeavyUnits() {
      
      myHeavyUnits_ = 0;
      onChanged();
      return this;
    }

    private int myLightUnits_ ;
    /**
     * <code>int32 my_light_units = 20;</code>
     * @return The myLightUnits.
     */
    @java.lang.Override
    public int getMyLightUnits() {
      return myLightUnits_;
    }
    /**
     * <code>int32 my_light_units = 20;</code>
     * @param value The myLightUnits to set.
     * @return This builder for chaining.
     */
    public Builder setMyLightUnits(int value) {
      
      myLightUnits_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 my_light_units = 20;</code>
     * @return This builder for chaining.
     */
    public Builder clearMyLightUnits() {
      
      myLightUnits_ = 0;
      onChanged();
      return this;
    }

    private int myRangedUnits_ ;
    /**
     * <code>int32 my_ranged_units = 21;</code>
     * @return The myRangedUnits.
     */
    @java.lang.Override
    public int getMyRangedUnits() {
      return myRangedUnits_;
    }
    /**
     * <code>int32 my_ranged_units = 21;</code>
     * @param value The myRangedUnits to set.
     * @return This builder for chaining.
     */
    public Builder setMyRangedUnits(int value) {
      
      myRangedUnits_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 my_ranged_units = 21;</code>
     * @return This builder for chaining.
     */
    public Builder clearMyRangedUnits() {
      
      myRangedUnits_ = 0;
      onChanged();
      return this;
    }

    private int initialEnemyWorker_ ;
    /**
     * <code>int32 initial_enemy_worker = 22;</code>
     * @return The initialEnemyWorker.
     */
    @java.lang.Override
    public int getInitialEnemyWorker() {
      return initialEnemyWorker_;
    }
    /**
     * <code>int32 initial_enemy_worker = 22;</code>
     * @param value The initialEnemyWorker to set.
     * @return This builder for chaining.
     */
    public Builder setInitialEnemyWorker(int value) {
      
      initialEnemyWorker_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 initial_enemy_worker = 22;</code>
     * @return This builder for chaining.
     */
    public Builder clearInitialEnemyWorker() {
      
      initialEnemyWorker_ = 0;
      onChanged();
      return this;
    }

    private int observedEnemyWorker_ ;
    /**
     * <code>int32 observed_enemy_worker = 23;</code>
     * @return The observedEnemyWorker.
     */
    @java.lang.Override
    public int getObservedEnemyWorker() {
      return observedEnemyWorker_;
    }
    /**
     * <code>int32 observed_enemy_worker = 23;</code>
     * @param value The observedEnemyWorker to set.
     * @return This builder for chaining.
     */
    public Builder setObservedEnemyWorker(int value) {
      
      observedEnemyWorker_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 observed_enemy_worker = 23;</code>
     * @return This builder for chaining.
     */
    public Builder clearObservedEnemyWorker() {
      
      observedEnemyWorker_ = 0;
      onChanged();
      return this;
    }

    private int observedEnemyHeavy_ ;
    /**
     * <code>int32 observed_enemy_heavy = 24;</code>
     * @return The observedEnemyHeavy.
     */
    @java.lang.Override
    public int getObservedEnemyHeavy() {
      return observedEnemyHeavy_;
    }
    /**
     * <code>int32 observed_enemy_heavy = 24;</code>
     * @param value The observedEnemyHeavy to set.
     * @return This builder for chaining.
     */
    public Builder setObservedEnemyHeavy(int value) {
      
      observedEnemyHeavy_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 observed_enemy_heavy = 24;</code>
     * @return This builder for chaining.
     */
    public Builder clearObservedEnemyHeavy() {
      
      observedEnemyHeavy_ = 0;
      onChanged();
      return this;
    }

    private int observedEnemyLight_ ;
    /**
     * <code>int32 observed_enemy_light = 25;</code>
     * @return The observedEnemyLight.
     */
    @java.lang.Override
    public int getObservedEnemyLight() {
      return observedEnemyLight_;
    }
    /**
     * <code>int32 observed_enemy_light = 25;</code>
     * @param value The observedEnemyLight to set.
     * @return This builder for chaining.
     */
    public Builder setObservedEnemyLight(int value) {
      
      observedEnemyLight_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 observed_enemy_light = 25;</code>
     * @return This builder for chaining.
     */
    public Builder clearObservedEnemyLight() {
      
      observedEnemyLight_ = 0;
      onChanged();
      return this;
    }

    private int observedEnemyRanged_ ;
    /**
     * <code>int32 observed_enemy_ranged = 26;</code>
     * @return The observedEnemyRanged.
     */
    @java.lang.Override
    public int getObservedEnemyRanged() {
      return observedEnemyRanged_;
    }
    /**
     * <code>int32 observed_enemy_ranged = 26;</code>
     * @param value The observedEnemyRanged to set.
     * @return This builder for chaining.
     */
    public Builder setObservedEnemyRanged(int value) {
      
      observedEnemyRanged_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 observed_enemy_ranged = 26;</code>
     * @return This builder for chaining.
     */
    public Builder clearObservedEnemyRanged() {
      
      observedEnemyRanged_ = 0;
      onChanged();
      return this;
    }

    private int observedEnemyWorkerInTotal_ ;
    /**
     * <code>int32 observed_enemy_worker_in_total = 27;</code>
     * @return The observedEnemyWorkerInTotal.
     */
    @java.lang.Override
    public int getObservedEnemyWorkerInTotal() {
      return observedEnemyWorkerInTotal_;
    }
    /**
     * <code>int32 observed_enemy_worker_in_total = 27;</code>
     * @param value The observedEnemyWorkerInTotal to set.
     * @return This builder for chaining.
     */
    public Builder setObservedEnemyWorkerInTotal(int value) {
      
      observedEnemyWorkerInTotal_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 observed_enemy_worker_in_total = 27;</code>
     * @return This builder for chaining.
     */
    public Builder clearObservedEnemyWorkerInTotal() {
      
      observedEnemyWorkerInTotal_ = 0;
      onChanged();
      return this;
    }

    private int observedEnemyHeavyInTotal_ ;
    /**
     * <code>int32 observed_enemy_heavy_in_total = 28;</code>
     * @return The observedEnemyHeavyInTotal.
     */
    @java.lang.Override
    public int getObservedEnemyHeavyInTotal() {
      return observedEnemyHeavyInTotal_;
    }
    /**
     * <code>int32 observed_enemy_heavy_in_total = 28;</code>
     * @param value The observedEnemyHeavyInTotal to set.
     * @return This builder for chaining.
     */
    public Builder setObservedEnemyHeavyInTotal(int value) {
      
      observedEnemyHeavyInTotal_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 observed_enemy_heavy_in_total = 28;</code>
     * @return This builder for chaining.
     */
    public Builder clearObservedEnemyHeavyInTotal() {
      
      observedEnemyHeavyInTotal_ = 0;
      onChanged();
      return this;
    }

    private int observedEnemyLightInTotal_ ;
    /**
     * <code>int32 observed_enemy_light_in_total = 29;</code>
     * @return The observedEnemyLightInTotal.
     */
    @java.lang.Override
    public int getObservedEnemyLightInTotal() {
      return observedEnemyLightInTotal_;
    }
    /**
     * <code>int32 observed_enemy_light_in_total = 29;</code>
     * @param value The observedEnemyLightInTotal to set.
     * @return This builder for chaining.
     */
    public Builder setObservedEnemyLightInTotal(int value) {
      
      observedEnemyLightInTotal_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 observed_enemy_light_in_total = 29;</code>
     * @return This builder for chaining.
     */
    public Builder clearObservedEnemyLightInTotal() {
      
      observedEnemyLightInTotal_ = 0;
      onChanged();
      return this;
    }

    private int observedEnemyRangedInTotal_ ;
    /**
     * <code>int32 observed_enemy_ranged_in_total = 30;</code>
     * @return The observedEnemyRangedInTotal.
     */
    @java.lang.Override
    public int getObservedEnemyRangedInTotal() {
      return observedEnemyRangedInTotal_;
    }
    /**
     * <code>int32 observed_enemy_ranged_in_total = 30;</code>
     * @param value The observedEnemyRangedInTotal to set.
     * @return This builder for chaining.
     */
    public Builder setObservedEnemyRangedInTotal(int value) {
      
      observedEnemyRangedInTotal_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 observed_enemy_ranged_in_total = 30;</code>
     * @return This builder for chaining.
     */
    public Builder clearObservedEnemyRangedInTotal() {
      
      observedEnemyRangedInTotal_ = 0;
      onChanged();
      return this;
    }

    private int solverType_ ;
    /**
     * <code>int32 solver_type = 31;</code>
     * @return The solverType.
     */
    @java.lang.Override
    public int getSolverType() {
      return solverType_;
    }
    /**
     * <code>int32 solver_type = 31;</code>
     * @param value The solverType to set.
     * @return This builder for chaining.
     */
    public Builder setSolverType(int value) {
      
      solverType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 solver_type = 31;</code>
     * @return This builder for chaining.
     */
    public Builder clearSolverType() {
      
      solverType_ = 0;
      onChanged();
      return this;
    }

    private int nbSamples_ ;
    /**
     * <code>int32 nb_samples = 32;</code>
     * @return The nbSamples.
     */
    @java.lang.Override
    public int getNbSamples() {
      return nbSamples_;
    }
    /**
     * <code>int32 nb_samples = 32;</code>
     * @param value The nbSamples to set.
     * @return This builder for chaining.
     */
    public Builder setNbSamples(int value) {
      
      nbSamples_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 nb_samples = 32;</code>
     * @return This builder for chaining.
     */
    public Builder clearNbSamples() {
      
      nbSamples_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GameStateBuffer)
  }

  // @@protoc_insertion_point(class_scope:GameStateBuffer)
  private static final com.microphantom.protos.GameStateBuffer DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.microphantom.protos.GameStateBuffer();
  }

  public static com.microphantom.protos.GameStateBuffer getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GameStateBuffer>
      PARSER = new com.google.protobuf.AbstractParser<GameStateBuffer>() {
    @java.lang.Override
    public GameStateBuffer parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GameStateBuffer(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GameStateBuffer> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GameStateBuffer> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.microphantom.protos.GameStateBuffer getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

