// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: microphantom.proto

package com.microphantom.protos;

public final class MicroPhantomProtos {
  private MicroPhantomProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GameStateBuffer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GameStateBuffer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SolutionBuffer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SolutionBuffer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022microphantom.proto\"\370\006\n\017GameStateBuffer" +
      "\022\014\n\004time\030\001 \001(\005\022\023\n\013nb_barracks\030\002 \001(\005\022\"\n\032m" +
      "in_distance_resource_base\030\003 \001(\005\022\"\n\032max_d" +
      "istance_resource_base\030\004 \001(\005\022\027\n\017no_initia" +
      "l_base\030\005 \001(\005\022\033\n\023no_initial_barracks\030\006 \001(" +
      "\005\022\021\n\tresources\030\007 \001(\005\022\031\n\021initial_resource" +
      "s\030\010 \001(\005\022\034\n\024enemy_resources_loss\030\t \001(\005\022\030\n" +
      "\020worker_move_time\030\n \001(\005\022\033\n\023worker_harves" +
      "t_time\030\013 \001(\005\022\032\n\022worker_return_time\030\014 \001(\005" +
      "\022\026\n\016harvest_amount\030\r \001(\005\022\021\n\tbase_cost\030\016 " +
      "\001(\005\022\025\n\rbarracks_cost\030\017 \001(\005\022\022\n\nheavy_cost" +
      "\030\020 \001(\005\022\022\n\nlight_cost\030\021 \001(\005\022\023\n\013ranged_cos" +
      "t\030\022 \001(\005\022\026\n\016my_heavy_units\030\023 \001(\005\022\026\n\016my_li" +
      "ght_units\030\024 \001(\005\022\027\n\017my_ranged_units\030\025 \001(\005" +
      "\022\034\n\024initial_enemy_worker\030\026 \001(\005\022\035\n\025observ" +
      "ed_enemy_worker\030\027 \001(\005\022\034\n\024observed_enemy_" +
      "heavy\030\030 \001(\005\022\034\n\024observed_enemy_light\030\031 \001(" +
      "\005\022\035\n\025observed_enemy_ranged\030\032 \001(\005\022&\n\036obse" +
      "rved_enemy_worker_in_total\030\033 \001(\005\022%\n\035obse" +
      "rved_enemy_heavy_in_total\030\034 \001(\005\022%\n\035obser" +
      "ved_enemy_light_in_total\030\035 \001(\005\022&\n\036observ" +
      "ed_enemy_ranged_in_total\030\036 \001(\005\022\023\n\013solver" +
      "_type\030\037 \001(\005\022\022\n\nnb_samples\030  \001(\005\"S\n\016Solut" +
      "ionBuffer\022\024\n\014number_heavy\030\001 \001(\005\022\024\n\014numbe" +
      "r_light\030\002 \001(\005\022\025\n\rnumber_ranged\030\003 \001(\005B/\n\027" +
      "com.microphantom.protosB\022MicroPhantomPro" +
      "tosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GameStateBuffer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GameStateBuffer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GameStateBuffer_descriptor,
        new java.lang.String[] { "Time", "NbBarracks", "MinDistanceResourceBase", "MaxDistanceResourceBase", "NoInitialBase", "NoInitialBarracks", "Resources", "InitialResources", "EnemyResourcesLoss", "WorkerMoveTime", "WorkerHarvestTime", "WorkerReturnTime", "HarvestAmount", "BaseCost", "BarracksCost", "HeavyCost", "LightCost", "RangedCost", "MyHeavyUnits", "MyLightUnits", "MyRangedUnits", "InitialEnemyWorker", "ObservedEnemyWorker", "ObservedEnemyHeavy", "ObservedEnemyLight", "ObservedEnemyRanged", "ObservedEnemyWorkerInTotal", "ObservedEnemyHeavyInTotal", "ObservedEnemyLightInTotal", "ObservedEnemyRangedInTotal", "SolverType", "NbSamples", });
    internal_static_SolutionBuffer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SolutionBuffer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SolutionBuffer_descriptor,
        new java.lang.String[] { "NumberHeavy", "NumberLight", "NumberRanged", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
