// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: microphantom.proto

package com.microphantom.protos;

/**
 * Protobuf type {@code SolutionBuffer}
 */
public final class SolutionBuffer extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SolutionBuffer)
    SolutionBufferOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SolutionBuffer.newBuilder() to construct.
  private SolutionBuffer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SolutionBuffer() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SolutionBuffer();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SolutionBuffer(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            numberHeavy_ = input.readInt32();
            break;
          }
          case 16: {

            numberLight_ = input.readInt32();
            break;
          }
          case 24: {

            numberRanged_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.microphantom.protos.MicroPhantomProtos.internal_static_SolutionBuffer_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.microphantom.protos.MicroPhantomProtos.internal_static_SolutionBuffer_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.microphantom.protos.SolutionBuffer.class, com.microphantom.protos.SolutionBuffer.Builder.class);
  }

  public static final int NUMBER_HEAVY_FIELD_NUMBER = 1;
  private int numberHeavy_;
  /**
   * <code>int32 number_heavy = 1;</code>
   * @return The numberHeavy.
   */
  @java.lang.Override
  public int getNumberHeavy() {
    return numberHeavy_;
  }

  public static final int NUMBER_LIGHT_FIELD_NUMBER = 2;
  private int numberLight_;
  /**
   * <code>int32 number_light = 2;</code>
   * @return The numberLight.
   */
  @java.lang.Override
  public int getNumberLight() {
    return numberLight_;
  }

  public static final int NUMBER_RANGED_FIELD_NUMBER = 3;
  private int numberRanged_;
  /**
   * <code>int32 number_ranged = 3;</code>
   * @return The numberRanged.
   */
  @java.lang.Override
  public int getNumberRanged() {
    return numberRanged_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (numberHeavy_ != 0) {
      output.writeInt32(1, numberHeavy_);
    }
    if (numberLight_ != 0) {
      output.writeInt32(2, numberLight_);
    }
    if (numberRanged_ != 0) {
      output.writeInt32(3, numberRanged_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (numberHeavy_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, numberHeavy_);
    }
    if (numberLight_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, numberLight_);
    }
    if (numberRanged_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, numberRanged_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.microphantom.protos.SolutionBuffer)) {
      return super.equals(obj);
    }
    com.microphantom.protos.SolutionBuffer other = (com.microphantom.protos.SolutionBuffer) obj;

    if (getNumberHeavy()
        != other.getNumberHeavy()) return false;
    if (getNumberLight()
        != other.getNumberLight()) return false;
    if (getNumberRanged()
        != other.getNumberRanged()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NUMBER_HEAVY_FIELD_NUMBER;
    hash = (53 * hash) + getNumberHeavy();
    hash = (37 * hash) + NUMBER_LIGHT_FIELD_NUMBER;
    hash = (53 * hash) + getNumberLight();
    hash = (37 * hash) + NUMBER_RANGED_FIELD_NUMBER;
    hash = (53 * hash) + getNumberRanged();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.microphantom.protos.SolutionBuffer parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.microphantom.protos.SolutionBuffer parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.microphantom.protos.SolutionBuffer parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.microphantom.protos.SolutionBuffer parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.microphantom.protos.SolutionBuffer parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.microphantom.protos.SolutionBuffer parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.microphantom.protos.SolutionBuffer parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.microphantom.protos.SolutionBuffer parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.microphantom.protos.SolutionBuffer parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.microphantom.protos.SolutionBuffer parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.microphantom.protos.SolutionBuffer parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.microphantom.protos.SolutionBuffer parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.microphantom.protos.SolutionBuffer prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SolutionBuffer}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SolutionBuffer)
      com.microphantom.protos.SolutionBufferOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.microphantom.protos.MicroPhantomProtos.internal_static_SolutionBuffer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.microphantom.protos.MicroPhantomProtos.internal_static_SolutionBuffer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.microphantom.protos.SolutionBuffer.class, com.microphantom.protos.SolutionBuffer.Builder.class);
    }

    // Construct using com.microphantom.protos.SolutionBuffer.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      numberHeavy_ = 0;

      numberLight_ = 0;

      numberRanged_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.microphantom.protos.MicroPhantomProtos.internal_static_SolutionBuffer_descriptor;
    }

    @java.lang.Override
    public com.microphantom.protos.SolutionBuffer getDefaultInstanceForType() {
      return com.microphantom.protos.SolutionBuffer.getDefaultInstance();
    }

    @java.lang.Override
    public com.microphantom.protos.SolutionBuffer build() {
      com.microphantom.protos.SolutionBuffer result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.microphantom.protos.SolutionBuffer buildPartial() {
      com.microphantom.protos.SolutionBuffer result = new com.microphantom.protos.SolutionBuffer(this);
      result.numberHeavy_ = numberHeavy_;
      result.numberLight_ = numberLight_;
      result.numberRanged_ = numberRanged_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.microphantom.protos.SolutionBuffer) {
        return mergeFrom((com.microphantom.protos.SolutionBuffer)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.microphantom.protos.SolutionBuffer other) {
      if (other == com.microphantom.protos.SolutionBuffer.getDefaultInstance()) return this;
      if (other.getNumberHeavy() != 0) {
        setNumberHeavy(other.getNumberHeavy());
      }
      if (other.getNumberLight() != 0) {
        setNumberLight(other.getNumberLight());
      }
      if (other.getNumberRanged() != 0) {
        setNumberRanged(other.getNumberRanged());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.microphantom.protos.SolutionBuffer parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.microphantom.protos.SolutionBuffer) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int numberHeavy_ ;
    /**
     * <code>int32 number_heavy = 1;</code>
     * @return The numberHeavy.
     */
    @java.lang.Override
    public int getNumberHeavy() {
      return numberHeavy_;
    }
    /**
     * <code>int32 number_heavy = 1;</code>
     * @param value The numberHeavy to set.
     * @return This builder for chaining.
     */
    public Builder setNumberHeavy(int value) {
      
      numberHeavy_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 number_heavy = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumberHeavy() {
      
      numberHeavy_ = 0;
      onChanged();
      return this;
    }

    private int numberLight_ ;
    /**
     * <code>int32 number_light = 2;</code>
     * @return The numberLight.
     */
    @java.lang.Override
    public int getNumberLight() {
      return numberLight_;
    }
    /**
     * <code>int32 number_light = 2;</code>
     * @param value The numberLight to set.
     * @return This builder for chaining.
     */
    public Builder setNumberLight(int value) {
      
      numberLight_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 number_light = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumberLight() {
      
      numberLight_ = 0;
      onChanged();
      return this;
    }

    private int numberRanged_ ;
    /**
     * <code>int32 number_ranged = 3;</code>
     * @return The numberRanged.
     */
    @java.lang.Override
    public int getNumberRanged() {
      return numberRanged_;
    }
    /**
     * <code>int32 number_ranged = 3;</code>
     * @param value The numberRanged to set.
     * @return This builder for chaining.
     */
    public Builder setNumberRanged(int value) {
      
      numberRanged_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 number_ranged = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumberRanged() {
      
      numberRanged_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SolutionBuffer)
  }

  // @@protoc_insertion_point(class_scope:SolutionBuffer)
  private static final com.microphantom.protos.SolutionBuffer DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.microphantom.protos.SolutionBuffer();
  }

  public static com.microphantom.protos.SolutionBuffer getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SolutionBuffer>
      PARSER = new com.google.protobuf.AbstractParser<SolutionBuffer>() {
    @java.lang.Override
    public SolutionBuffer parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SolutionBuffer(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SolutionBuffer> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SolutionBuffer> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.microphantom.protos.SolutionBuffer getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

