// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: microphantom.proto

package com.microphantom.protos;

public interface SolutionBufferOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SolutionBuffer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 number_heavy = 1;</code>
   * @return The numberHeavy.
   */
  int getNumberHeavy();

  /**
   * <code>int32 number_light = 2;</code>
   * @return The numberLight.
   */
  int getNumberLight();

  /**
   * <code>int32 number_ranged = 3;</code>
   * @return The numberRanged.
   */
  int getNumberRanged();
}
